// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AbortActor implements abortActor operation.
	//
	// POST /agents/{agentID}/abort
	AbortActor(ctx context.Context, params AbortActorParams) (*AbortResult, error)
	// AddDocument implements addDocument operation.
	//
	// POST /datasets/{id}/documents
	AddDocument(ctx context.Context, req *AddDocumentRequest, params AddDocumentParams) (*DatasetDocument, error)
	// AddModel implements addModel operation.
	//
	// POST /models
	AddModel(ctx context.Context, req *AddModelRequest) (*ModelInfo, error)
	// ChangePassword implements changePassword operation.
	//
	// POST /auth/change-password
	ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*OkResponse, error)
	// CompileGraph implements compileGraph operation.
	//
	// POST /agents/{id}/compile
	CompileGraph(ctx context.Context, params CompileGraphParams) (*CompileResult, error)
	// ConfigureProvider implements configureProvider operation.
	//
	// POST /providers/{name}/configure
	ConfigureProvider(ctx context.Context, req *ConfigureProviderRequest, params ConfigureProviderParams) error
	// CreateAgent implements createAgent operation.
	//
	// POST /agents
	CreateAgent(ctx context.Context, req *CreateAgentRequest) (*Agent, error)
	// CreateDataset implements createDataset operation.
	//
	// POST /datasets
	CreateDataset(ctx context.Context, req *CreateDatasetRequest) (*Dataset, error)
	// CreateTemplate implements createTemplate operation.
	//
	// POST /templates
	CreateTemplate(ctx context.Context, req *CreateTemplateRequest) (*GraphTemplate, error)
	// CreateWSTicket implements createWSTicket operation.
	//
	// POST /ws-ticket
	CreateWSTicket(ctx context.Context) (*WSTicketResponse, error)
	// DeleteAgent implements deleteAgent operation.
	//
	// DELETE /agents/{id}
	DeleteAgent(ctx context.Context, params DeleteAgentParams) error
	// DeleteDataset implements deleteDataset operation.
	//
	// DELETE /datasets/{id}
	DeleteDataset(ctx context.Context, params DeleteDatasetParams) error
	// DeleteDocument implements deleteDocument operation.
	//
	// DELETE /datasets/{id}/documents/{docId}
	DeleteDocument(ctx context.Context, params DeleteDocumentParams) error
	// DeleteMemory implements deleteMemory operation.
	//
	// DELETE /memories/{entryID}
	DeleteMemory(ctx context.Context, params DeleteMemoryParams) error
	// DeleteModel implements deleteModel operation.
	//
	// DELETE /models/{modelID}
	DeleteModel(ctx context.Context, params DeleteModelParams) error
	// DeletePlugin implements deletePlugin operation.
	//
	// DELETE /plugins/{name}
	DeletePlugin(ctx context.Context, params DeletePluginParams) error
	// DeleteSkill implements deleteSkill operation.
	//
	// DELETE /skills/{name}
	DeleteSkill(ctx context.Context, params DeleteSkillParams) error
	// DeleteTemplate implements deleteTemplate operation.
	//
	// DELETE /templates/{name}
	DeleteTemplate(ctx context.Context, params DeleteTemplateParams) error
	// DiffVersions implements diffVersions operation.
	//
	// GET /agents/{id}/versions/diff
	DiffVersions(ctx context.Context, params DiffVersionsParams) (*VersionDiff, error)
	// DisablePlugin implements disablePlugin operation.
	//
	// POST /plugins/{name}/disable
	DisablePlugin(ctx context.Context, params DisablePluginParams) (*PluginInfo, error)
	// DryRun implements dryRun operation.
	//
	// POST /agents/{id}/dryrun
	DryRun(ctx context.Context, params DryRunParams) (*DryRunResult, error)
	// EnablePlugin implements enablePlugin operation.
	//
	// POST /plugins/{name}/enable
	EnablePlugin(ctx context.Context, req OptPluginConfig, params EnablePluginParams) (*PluginInfo, error)
	// ExportAgent implements exportAgent operation.
	//
	// GET /agents/{id}/export
	ExportAgent(ctx context.Context, params ExportAgentParams) (*ExportAgentOKHeaders, error)
	// GetAgent implements getAgent operation.
	//
	// GET /agents/{id}
	GetAgent(ctx context.Context, params GetAgentParams) (*Agent, error)
	// GetAuthStatus implements getAuthStatus operation.
	//
	// Returns whether owner credentials have been initialized.
	//
	// GET /auth/status
	GetAuthStatus(ctx context.Context) (*AuthStatus, error)
	// GetChannelTypes implements getChannelTypes operation.
	//
	// GET /channel-types
	GetChannelTypes(ctx context.Context) (*ChannelTypeList, error)
	// GetDataset implements getDataset operation.
	//
	// GET /datasets/{id}
	GetDataset(ctx context.Context, params GetDatasetParams) (*Dataset, error)
	// GetGraphHistory implements getGraphHistory operation.
	//
	// GET /agents/{id}/graph/history
	GetGraphHistory(ctx context.Context, params GetGraphHistoryParams) (*GraphOperationList, error)
	// GetKanbanCards implements getKanbanCards operation.
	//
	// GET /kanban/cards
	GetKanbanCards(ctx context.Context) (*KanbanCardList, error)
	// GetKanbanTimeline implements getKanbanTimeline operation.
	//
	// GET /kanban/timeline
	GetKanbanTimeline(ctx context.Context) (*KanbanTimeline, error)
	// GetKanbanTopology implements getKanbanTopology operation.
	//
	// GET /kanban/topology
	GetKanbanTopology(ctx context.Context) (*KanbanTopology, error)
	// GetMemoryStats implements getMemoryStats operation.
	//
	// GET /stats/memory
	GetMemoryStats(ctx context.Context) (*MemoryStats, error)
	// GetMessages implements getMessages operation.
	//
	// GET /conversations/{id}/messages
	GetMessages(ctx context.Context, params GetMessagesParams) (*MessageList, error)
	// GetMonitoringDiagnostics implements getMonitoringDiagnostics operation.
	//
	// GET /monitoring/diagnostics
	GetMonitoringDiagnostics(ctx context.Context, params GetMonitoringDiagnosticsParams) (*MonitoringDiagnostics, error)
	// GetMonitoringRuntime implements getMonitoringRuntime operation.
	//
	// GET /monitoring/runtime
	GetMonitoringRuntime(ctx context.Context) (*RuntimeManagerStats, error)
	// GetMonitoringSummary implements getMonitoringSummary operation.
	//
	// GET /monitoring/summary
	GetMonitoringSummary(ctx context.Context, params GetMonitoringSummaryParams) (*MonitoringSummary, error)
	// GetMonitoringTimeseries implements getMonitoringTimeseries operation.
	//
	// GET /monitoring/timeseries
	GetMonitoringTimeseries(ctx context.Context, params GetMonitoringTimeseriesParams) (*MonitoringTimeseries, error)
	// GetPlugin implements getPlugin operation.
	//
	// GET /plugins/{name}
	GetPlugin(ctx context.Context, params GetPluginParams) (*PluginDetail, error)
	// GetRunStats implements getRunStats operation.
	//
	// GET /stats/runs
	GetRunStats(ctx context.Context, params GetRunStatsParams) (*DailyRunStatsList, error)
	// GetRunStatus implements getRunStatus operation.
	//
	// GET /workflows/runs/{id}/status
	GetRunStatus(ctx context.Context, params GetRunStatusParams) (*WorkflowRun, error)
	// GetRuntimeStats implements getRuntimeStats operation.
	//
	// GET /stats/runtime
	GetRuntimeStats(ctx context.Context) (*RuntimeStats, error)
	// GetSession implements getSession operation.
	//
	// GET /auth/session
	GetSession(ctx context.Context) (*SessionInfo, error)
	// GetStats implements getStats operation.
	//
	// GET /stats
	GetStats(ctx context.Context) (*StatsOverview, error)
	// GetWorkflowRun implements getWorkflowRun operation.
	//
	// GET /workflows/runs/{id}
	GetWorkflowRun(ctx context.Context, params GetWorkflowRunParams) (*WorkflowRun, error)
	// HealthCheck implements healthCheck operation.
	//
	// GET /healthz
	HealthCheck(ctx context.Context) (*HealthStatus, error)
	// ImportAgent implements importAgent operation.
	//
	// POST /agents/{id}/import
	ImportAgent(ctx context.Context, req *ImportRequest, params ImportAgentParams) (*ImportResult, error)
	// InstallSkill implements installSkill operation.
	//
	// POST /skills/install
	InstallSkill(ctx context.Context, req *InstallSkillRequest) (*SkillInstallResult, error)
	// InstantiateTemplate implements instantiateTemplate operation.
	//
	// POST /templates/{name}/instantiate
	InstantiateTemplate(ctx context.Context, req OptTemplateParams, params InstantiateTemplateParams) (*GraphDefinition, error)
	// ListAgents implements listAgents operation.
	//
	// GET /agents
	ListAgents(ctx context.Context, params ListAgentsParams) (*AgentList, error)
	// ListConversations implements listConversations operation.
	//
	// GET /conversations
	ListConversations(ctx context.Context, params ListConversationsParams) (*ConversationList, error)
	// ListDatasets implements listDatasets operation.
	//
	// GET /datasets
	ListDatasets(ctx context.Context) (*DatasetList, error)
	// ListDocuments implements listDocuments operation.
	//
	// GET /datasets/{id}/documents
	ListDocuments(ctx context.Context, params ListDocumentsParams) (*DocumentList, error)
	// ListMemories implements listMemories operation.
	//
	// GET /memories
	ListMemories(ctx context.Context, params ListMemoriesParams) (*MemoryEntryList, error)
	// ListModels implements listModels operation.
	//
	// GET /models
	ListModels(ctx context.Context) (*ModelList, error)
	// ListNodeTypes implements listNodeTypes operation.
	//
	// GET /node-types
	ListNodeTypes(ctx context.Context) (*NodeTypeList, error)
	// ListPlugins implements listPlugins operation.
	//
	// GET /plugins
	ListPlugins(ctx context.Context, params ListPluginsParams) (*PluginList, error)
	// ListProviders implements listProviders operation.
	//
	// GET /providers
	ListProviders(ctx context.Context) (*ProviderList, error)
	// ListSkills implements listSkills operation.
	//
	// GET /skills
	ListSkills(ctx context.Context) (*SkillList, error)
	// ListTemplates implements listTemplates operation.
	//
	// GET /templates
	ListTemplates(ctx context.Context) (*TemplateList, error)
	// ListTools implements listTools operation.
	//
	// GET /tools
	ListTools(ctx context.Context) (*ToolList, error)
	// ListVersions implements listVersions operation.
	//
	// GET /agents/{id}/versions
	ListVersions(ctx context.Context, params ListVersionsParams) (*GraphVersionList, error)
	// ListWorkflowRuns implements listWorkflowRuns operation.
	//
	// GET /workflows/runs
	ListWorkflowRuns(ctx context.Context, params ListWorkflowRunsParams) (*WorkflowRunList, error)
	// Login implements login operation.
	//
	// POST /auth/login
	Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error)
	// Logout implements logout operation.
	//
	// POST /auth/logout
	Logout(ctx context.Context) error
	// PublishVersion implements publishVersion operation.
	//
	// POST /agents/{id}/versions/publish
	PublishVersion(ctx context.Context, req *PublishVersionRequest, params PublishVersionParams) (*GraphVersion, error)
	// QueryDocuments implements queryDocuments operation.
	//
	// POST /datasets/{id}/query
	QueryDocuments(ctx context.Context, req *DatasetQueryRequest, params QueryDocumentsParams) (*QueryResultList, error)
	// ReloadPlugins implements reloadPlugins operation.
	//
	// POST /plugins/reload
	ReloadPlugins(ctx context.Context) (*PluginReloadResult, error)
	// ReprocessDocument implements reprocessDocument operation.
	//
	// Resets processing_status to "pending" and submits the document
	// to the platform's context worker. Useful for retrying a doc
	// that failed during the initial generation (e.g. transient LLM
	// error). Returns the patched document row.
	//
	// POST /datasets/{id}/documents/{docId}/reprocess
	ReprocessDocument(ctx context.Context, params ReprocessDocumentParams) (*DatasetDocument, error)
	// RollbackVersion implements rollbackVersion operation.
	//
	// POST /agents/{id}/versions/{ver}/rollback
	RollbackVersion(ctx context.Context, params RollbackVersionParams) (*GraphVersion, error)
	// SetDefaultModel implements setDefaultModel operation.
	//
	// PUT /models/default
	SetDefaultModel(ctx context.Context, req *SetDefaultModelRequest) error
	// SetupAuth implements setupAuth operation.
	//
	// One-time owner credential bootstrap. Returns 409 if already initialized.
	//
	// POST /auth/setup
	SetupAuth(ctx context.Context, req *SetupRequest) (*OkResponse, error)
	// StartConversationRun implements startConversationRun operation.
	//
	// Starts an agent run on this conversation. This replaces the previous
	// `POST /chat/stream` SSE endpoint: the call returns immediately with the
	// identifiers needed to subscribe to the resulting envelope stream.
	// All token, tool-call and completion events are published to the event
	// log; clients consume them via
	// `GET /api/events?partition=card:{id}&since={last_seq}` (or the WS/SSE
	// envelope channels exposed by the same surface).
	//
	// POST /conversations/{id}/runs
	StartConversationRun(ctx context.Context, req *ChatRequest, params StartConversationRunParams) (*ChatStartResponse, error)
	// SubmitApproval implements submitApproval operation.
	//
	// Submit a HITL approval decision for a paused agent run on this conversation.
	// This is the command-side replacement of the deprecated `POST /chat/resume/stream`:
	// the decision is injected into the saved BoardSnapshot and the agent resumes.
	// The resulting envelopes (agent.stream.delta, kanban.card.*, ...) are emitted to
	// the event log; subscribe to `GET /api/events?partition=card:{id}` to follow them.
	//
	// POST /conversations/{id}/approval
	SubmitApproval(ctx context.Context, req *ApprovalDecisionRequest, params SubmitApprovalParams) (*ApprovalDecisionResponse, error)
	// UpdateAgent implements updateAgent operation.
	//
	// PUT /agents/{id}
	UpdateAgent(ctx context.Context, req *UpdateAgentRequest, params UpdateAgentParams) (*Agent, error)
	// UpdateAllSkills implements updateAllSkills operation.
	//
	// POST /skills/update-all
	UpdateAllSkills(ctx context.Context) (*SkillUpdateAllResult, error)
	// UpdateMemory implements updateMemory operation.
	//
	// PUT /memories/{entryID}
	UpdateMemory(ctx context.Context, req *UpdateMemoryRequest, params UpdateMemoryParams) (*MemoryEntry, error)
	// UpdatePluginConfig implements updatePluginConfig operation.
	//
	// PUT /plugins/{name}/config
	UpdatePluginConfig(ctx context.Context, req PluginConfig, params UpdatePluginConfigParams) (*PluginInfo, error)
	// UpdateSkill implements updateSkill operation.
	//
	// PUT /skills/{name}
	UpdateSkill(ctx context.Context, params UpdateSkillParams) (*SkillUpdateResult, error)
	// UploadPlugin implements uploadPlugin operation.
	//
	// POST /plugins/upload
	UploadPlugin(ctx context.Context, req *UploadPluginReq) (*PluginUploadResult, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
