// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles bearerAuth security.
	// Same JWT as cookieAuth, sent via the Authorization: Bearer header.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
	// HandleCookieAuth handles cookieAuth security.
	// JWT issued by `/auth/login`, set as HttpOnly cookie.
	HandleCookieAuth(ctx context.Context, operationName OperationName, t CookieAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesBearerAuth = map[string][]string{
	AbortActorOperation:               []string{},
	AddDocumentOperation:              []string{},
	AddModelOperation:                 []string{},
	ChangePasswordOperation:           []string{},
	CompileGraphOperation:             []string{},
	ConfigureProviderOperation:        []string{},
	CreateAgentOperation:              []string{},
	CreateDatasetOperation:            []string{},
	CreateTemplateOperation:           []string{},
	CreateWSTicketOperation:           []string{},
	DeleteAgentOperation:              []string{},
	DeleteDatasetOperation:            []string{},
	DeleteDocumentOperation:           []string{},
	DeleteMemoryOperation:             []string{},
	DeleteModelOperation:              []string{},
	DeletePluginOperation:             []string{},
	DeleteSkillOperation:              []string{},
	DeleteTemplateOperation:           []string{},
	DiffVersionsOperation:             []string{},
	DisablePluginOperation:            []string{},
	DryRunOperation:                   []string{},
	EnablePluginOperation:             []string{},
	ExportAgentOperation:              []string{},
	GetAgentOperation:                 []string{},
	GetChannelTypesOperation:          []string{},
	GetDatasetOperation:               []string{},
	GetGraphHistoryOperation:          []string{},
	GetKanbanCardsOperation:           []string{},
	GetKanbanTimelineOperation:        []string{},
	GetKanbanTopologyOperation:        []string{},
	GetMemoryStatsOperation:           []string{},
	GetMessagesOperation:              []string{},
	GetMonitoringDiagnosticsOperation: []string{},
	GetMonitoringRuntimeOperation:     []string{},
	GetMonitoringSummaryOperation:     []string{},
	GetMonitoringTimeseriesOperation:  []string{},
	GetPluginOperation:                []string{},
	GetRunStatsOperation:              []string{},
	GetRunStatusOperation:             []string{},
	GetRuntimeStatsOperation:          []string{},
	GetStatsOperation:                 []string{},
	GetWorkflowRunOperation:           []string{},
	ImportAgentOperation:              []string{},
	InstallSkillOperation:             []string{},
	InstantiateTemplateOperation:      []string{},
	ListAgentsOperation:               []string{},
	ListConversationsOperation:        []string{},
	ListDatasetsOperation:             []string{},
	ListDocumentsOperation:            []string{},
	ListMemoriesOperation:             []string{},
	ListModelsOperation:               []string{},
	ListNodeTypesOperation:            []string{},
	ListPluginsOperation:              []string{},
	ListProvidersOperation:            []string{},
	ListSkillsOperation:               []string{},
	ListTemplatesOperation:            []string{},
	ListToolsOperation:                []string{},
	ListVersionsOperation:             []string{},
	ListWorkflowRunsOperation:         []string{},
	PublishVersionOperation:           []string{},
	QueryDocumentsOperation:           []string{},
	ReloadPluginsOperation:            []string{},
	ReprocessDocumentOperation:        []string{},
	RollbackVersionOperation:          []string{},
	SetDefaultModelOperation:          []string{},
	StartConversationRunOperation:     []string{},
	SubmitApprovalOperation:           []string{},
	UpdateAgentOperation:              []string{},
	UpdateAllSkillsOperation:          []string{},
	UpdateMemoryOperation:             []string{},
	UpdatePluginConfigOperation:       []string{},
	UpdateSkillOperation:              []string{},
	UploadPluginOperation:             []string{},
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

var operationRolesCookieAuth = map[string][]string{
	AbortActorOperation:               []string{},
	AddDocumentOperation:              []string{},
	AddModelOperation:                 []string{},
	ChangePasswordOperation:           []string{},
	CompileGraphOperation:             []string{},
	ConfigureProviderOperation:        []string{},
	CreateAgentOperation:              []string{},
	CreateDatasetOperation:            []string{},
	CreateTemplateOperation:           []string{},
	CreateWSTicketOperation:           []string{},
	DeleteAgentOperation:              []string{},
	DeleteDatasetOperation:            []string{},
	DeleteDocumentOperation:           []string{},
	DeleteMemoryOperation:             []string{},
	DeleteModelOperation:              []string{},
	DeletePluginOperation:             []string{},
	DeleteSkillOperation:              []string{},
	DeleteTemplateOperation:           []string{},
	DiffVersionsOperation:             []string{},
	DisablePluginOperation:            []string{},
	DryRunOperation:                   []string{},
	EnablePluginOperation:             []string{},
	ExportAgentOperation:              []string{},
	GetAgentOperation:                 []string{},
	GetChannelTypesOperation:          []string{},
	GetDatasetOperation:               []string{},
	GetGraphHistoryOperation:          []string{},
	GetKanbanCardsOperation:           []string{},
	GetKanbanTimelineOperation:        []string{},
	GetKanbanTopologyOperation:        []string{},
	GetMemoryStatsOperation:           []string{},
	GetMessagesOperation:              []string{},
	GetMonitoringDiagnosticsOperation: []string{},
	GetMonitoringRuntimeOperation:     []string{},
	GetMonitoringSummaryOperation:     []string{},
	GetMonitoringTimeseriesOperation:  []string{},
	GetPluginOperation:                []string{},
	GetRunStatsOperation:              []string{},
	GetRunStatusOperation:             []string{},
	GetRuntimeStatsOperation:          []string{},
	GetStatsOperation:                 []string{},
	GetWorkflowRunOperation:           []string{},
	ImportAgentOperation:              []string{},
	InstallSkillOperation:             []string{},
	InstantiateTemplateOperation:      []string{},
	ListAgentsOperation:               []string{},
	ListConversationsOperation:        []string{},
	ListDatasetsOperation:             []string{},
	ListDocumentsOperation:            []string{},
	ListMemoriesOperation:             []string{},
	ListModelsOperation:               []string{},
	ListNodeTypesOperation:            []string{},
	ListPluginsOperation:              []string{},
	ListProvidersOperation:            []string{},
	ListSkillsOperation:               []string{},
	ListTemplatesOperation:            []string{},
	ListToolsOperation:                []string{},
	ListVersionsOperation:             []string{},
	ListWorkflowRunsOperation:         []string{},
	PublishVersionOperation:           []string{},
	QueryDocumentsOperation:           []string{},
	ReloadPluginsOperation:            []string{},
	ReprocessDocumentOperation:        []string{},
	RollbackVersionOperation:          []string{},
	SetDefaultModelOperation:          []string{},
	StartConversationRunOperation:     []string{},
	SubmitApprovalOperation:           []string{},
	UpdateAgentOperation:              []string{},
	UpdateAllSkillsOperation:          []string{},
	UpdateMemoryOperation:             []string{},
	UpdatePluginConfigOperation:       []string{},
	UpdateSkillOperation:              []string{},
	UploadPluginOperation:             []string{},
}

func (s *Server) securityCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t CookieAuth
	const parameterName = "flowcraft_token"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	t.Roles = operationRolesCookieAuth[operationName]
	rctx, err := s.sec.HandleCookieAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	// Same JWT as cookieAuth, sent via the Authorization: Bearer header.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
	// CookieAuth provides cookieAuth security value.
	// JWT issued by `/auth/login`, set as HttpOnly cookie.
	CookieAuth(ctx context.Context, operationName OperationName) (CookieAuth, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.CookieAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"CookieAuth\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "flowcraft_token",
		Value: t.APIKey,
	})
	return nil
}
