// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AbortActor implements abortActor operation.
//
// POST /agents/{agentID}/abort
func (UnimplementedHandler) AbortActor(ctx context.Context, params AbortActorParams) (r *AbortResult, _ error) {
	return r, ht.ErrNotImplemented
}

// AddDocument implements addDocument operation.
//
// POST /datasets/{id}/documents
func (UnimplementedHandler) AddDocument(ctx context.Context, req *AddDocumentRequest, params AddDocumentParams) (r *DatasetDocument, _ error) {
	return r, ht.ErrNotImplemented
}

// AddModel implements addModel operation.
//
// POST /models
func (UnimplementedHandler) AddModel(ctx context.Context, req *AddModelRequest) (r *ModelInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// ChangePassword implements changePassword operation.
//
// POST /auth/change-password
func (UnimplementedHandler) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (r *OkResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CompileGraph implements compileGraph operation.
//
// POST /agents/{id}/compile
func (UnimplementedHandler) CompileGraph(ctx context.Context, params CompileGraphParams) (r *CompileResult, _ error) {
	return r, ht.ErrNotImplemented
}

// ConfigureProvider implements configureProvider operation.
//
// POST /providers/{name}/configure
func (UnimplementedHandler) ConfigureProvider(ctx context.Context, req *ConfigureProviderRequest, params ConfigureProviderParams) error {
	return ht.ErrNotImplemented
}

// CreateAgent implements createAgent operation.
//
// POST /agents
func (UnimplementedHandler) CreateAgent(ctx context.Context, req *CreateAgentRequest) (r *Agent, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDataset implements createDataset operation.
//
// POST /datasets
func (UnimplementedHandler) CreateDataset(ctx context.Context, req *CreateDatasetRequest) (r *Dataset, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTemplate implements createTemplate operation.
//
// POST /templates
func (UnimplementedHandler) CreateTemplate(ctx context.Context, req *CreateTemplateRequest) (r *GraphTemplate, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWSTicket implements createWSTicket operation.
//
// Issues a single-use ticket scoped to one (partition, since) pair, as
// required by §12.3. The ticket is consumed by /api/events/ws on the
// first frame; subsequent subscribes on the same connection still go
// through the actor's policy. The TTL is 45s — enough to cover client
// retries but short enough that leaked tickets can't be replayed.
//
// POST /ws-ticket
func (UnimplementedHandler) CreateWSTicket(ctx context.Context, req *WSTicketRequest) (r *WSTicketResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAgent implements deleteAgent operation.
//
// DELETE /agents/{id}
func (UnimplementedHandler) DeleteAgent(ctx context.Context, params DeleteAgentParams) error {
	return ht.ErrNotImplemented
}

// DeleteDataset implements deleteDataset operation.
//
// DELETE /datasets/{id}
func (UnimplementedHandler) DeleteDataset(ctx context.Context, params DeleteDatasetParams) error {
	return ht.ErrNotImplemented
}

// DeleteDocument implements deleteDocument operation.
//
// DELETE /datasets/{id}/documents/{docId}
func (UnimplementedHandler) DeleteDocument(ctx context.Context, params DeleteDocumentParams) error {
	return ht.ErrNotImplemented
}

// DeleteMemory implements deleteMemory operation.
//
// DELETE /memories/{entryID}
func (UnimplementedHandler) DeleteMemory(ctx context.Context, params DeleteMemoryParams) error {
	return ht.ErrNotImplemented
}

// DeleteModel implements deleteModel operation.
//
// DELETE /models/{modelID}
func (UnimplementedHandler) DeleteModel(ctx context.Context, params DeleteModelParams) error {
	return ht.ErrNotImplemented
}

// DeletePlugin implements deletePlugin operation.
//
// DELETE /plugins/{name}
func (UnimplementedHandler) DeletePlugin(ctx context.Context, params DeletePluginParams) error {
	return ht.ErrNotImplemented
}

// DeleteSkill implements deleteSkill operation.
//
// DELETE /skills/{name}
func (UnimplementedHandler) DeleteSkill(ctx context.Context, params DeleteSkillParams) error {
	return ht.ErrNotImplemented
}

// DeleteTemplate implements deleteTemplate operation.
//
// DELETE /templates/{name}
func (UnimplementedHandler) DeleteTemplate(ctx context.Context, params DeleteTemplateParams) error {
	return ht.ErrNotImplemented
}

// DiffVersions implements diffVersions operation.
//
// GET /agents/{id}/versions/diff
func (UnimplementedHandler) DiffVersions(ctx context.Context, params DiffVersionsParams) (r *VersionDiff, _ error) {
	return r, ht.ErrNotImplemented
}

// DisablePlugin implements disablePlugin operation.
//
// POST /plugins/{name}/disable
func (UnimplementedHandler) DisablePlugin(ctx context.Context, params DisablePluginParams) (r *PluginInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// DryRun implements dryRun operation.
//
// POST /agents/{id}/dryrun
func (UnimplementedHandler) DryRun(ctx context.Context, params DryRunParams) (r *DryRunResult, _ error) {
	return r, ht.ErrNotImplemented
}

// EnablePlugin implements enablePlugin operation.
//
// POST /plugins/{name}/enable
func (UnimplementedHandler) EnablePlugin(ctx context.Context, req OptPluginConfig, params EnablePluginParams) (r *PluginInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// ExportAgent implements exportAgent operation.
//
// GET /agents/{id}/export
func (UnimplementedHandler) ExportAgent(ctx context.Context, params ExportAgentParams) (r *ExportAgentOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgent implements getAgent operation.
//
// GET /agents/{id}
func (UnimplementedHandler) GetAgent(ctx context.Context, params GetAgentParams) (r *Agent, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuthStatus implements getAuthStatus operation.
//
// Returns whether owner credentials have been initialized.
//
// GET /auth/status
func (UnimplementedHandler) GetAuthStatus(ctx context.Context) (r *AuthStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChannelTypes implements getChannelTypes operation.
//
// GET /channel-types
func (UnimplementedHandler) GetChannelTypes(ctx context.Context) (r *ChannelTypeList, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDataset implements getDataset operation.
//
// GET /datasets/{id}
func (UnimplementedHandler) GetDataset(ctx context.Context, params GetDatasetParams) (r *Dataset, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGraphHistory implements getGraphHistory operation.
//
// GET /agents/{id}/graph/history
func (UnimplementedHandler) GetGraphHistory(ctx context.Context, params GetGraphHistoryParams) (r *GraphOperationList, _ error) {
	return r, ht.ErrNotImplemented
}

// GetKanbanCards implements getKanbanCards operation.
//
// GET /kanban/cards
func (UnimplementedHandler) GetKanbanCards(ctx context.Context) (r *KanbanCardList, _ error) {
	return r, ht.ErrNotImplemented
}

// GetKanbanTimeline implements getKanbanTimeline operation.
//
// GET /kanban/timeline
func (UnimplementedHandler) GetKanbanTimeline(ctx context.Context) (r *KanbanTimeline, _ error) {
	return r, ht.ErrNotImplemented
}

// GetKanbanTopology implements getKanbanTopology operation.
//
// GET /kanban/topology
func (UnimplementedHandler) GetKanbanTopology(ctx context.Context) (r *KanbanTopology, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMemoryStats implements getMemoryStats operation.
//
// GET /stats/memory
func (UnimplementedHandler) GetMemoryStats(ctx context.Context) (r *MemoryStats, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMessages implements getMessages operation.
//
// GET /conversations/{id}/messages
func (UnimplementedHandler) GetMessages(ctx context.Context, params GetMessagesParams) (r *MessageList, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMonitoringDiagnostics implements getMonitoringDiagnostics operation.
//
// GET /monitoring/diagnostics
func (UnimplementedHandler) GetMonitoringDiagnostics(ctx context.Context, params GetMonitoringDiagnosticsParams) (r *MonitoringDiagnostics, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMonitoringRuntime implements getMonitoringRuntime operation.
//
// GET /monitoring/runtime
func (UnimplementedHandler) GetMonitoringRuntime(ctx context.Context) (r *RuntimeManagerStats, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMonitoringSummary implements getMonitoringSummary operation.
//
// GET /monitoring/summary
func (UnimplementedHandler) GetMonitoringSummary(ctx context.Context, params GetMonitoringSummaryParams) (r *MonitoringSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMonitoringTimeseries implements getMonitoringTimeseries operation.
//
// GET /monitoring/timeseries
func (UnimplementedHandler) GetMonitoringTimeseries(ctx context.Context, params GetMonitoringTimeseriesParams) (r *MonitoringTimeseries, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPlugin implements getPlugin operation.
//
// GET /plugins/{name}
func (UnimplementedHandler) GetPlugin(ctx context.Context, params GetPluginParams) (r *PluginDetail, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRunStats implements getRunStats operation.
//
// GET /stats/runs
func (UnimplementedHandler) GetRunStats(ctx context.Context, params GetRunStatsParams) (r *DailyRunStatsList, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRunStatus implements getRunStatus operation.
//
// GET /workflows/runs/{id}/status
func (UnimplementedHandler) GetRunStatus(ctx context.Context, params GetRunStatusParams) (r *WorkflowRun, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRuntimeStats implements getRuntimeStats operation.
//
// GET /stats/runtime
func (UnimplementedHandler) GetRuntimeStats(ctx context.Context) (r *RuntimeStats, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSession implements getSession operation.
//
// GET /auth/session
func (UnimplementedHandler) GetSession(ctx context.Context) (r *SessionInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStats implements getStats operation.
//
// GET /stats
func (UnimplementedHandler) GetStats(ctx context.Context) (r *StatsOverview, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkflowRun implements getWorkflowRun operation.
//
// GET /workflows/runs/{id}
func (UnimplementedHandler) GetWorkflowRun(ctx context.Context, params GetWorkflowRunParams) (r *WorkflowRun, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthCheck implements healthCheck operation.
//
// GET /healthz
func (UnimplementedHandler) HealthCheck(ctx context.Context) (r *HealthStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportAgent implements importAgent operation.
//
// POST /agents/{id}/import
func (UnimplementedHandler) ImportAgent(ctx context.Context, req *ImportRequest, params ImportAgentParams) (r *ImportResult, _ error) {
	return r, ht.ErrNotImplemented
}

// InstallSkill implements installSkill operation.
//
// POST /skills/install
func (UnimplementedHandler) InstallSkill(ctx context.Context, req *InstallSkillRequest) (r *SkillInstallResult, _ error) {
	return r, ht.ErrNotImplemented
}

// InstantiateTemplate implements instantiateTemplate operation.
//
// POST /templates/{name}/instantiate
func (UnimplementedHandler) InstantiateTemplate(ctx context.Context, req OptTemplateParams, params InstantiateTemplateParams) (r *GraphDefinition, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAgents implements listAgents operation.
//
// GET /agents
func (UnimplementedHandler) ListAgents(ctx context.Context, params ListAgentsParams) (r *AgentList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListConversations implements listConversations operation.
//
// GET /conversations
func (UnimplementedHandler) ListConversations(ctx context.Context, params ListConversationsParams) (r *ConversationList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDatasets implements listDatasets operation.
//
// GET /datasets
func (UnimplementedHandler) ListDatasets(ctx context.Context) (r *DatasetList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDocuments implements listDocuments operation.
//
// GET /datasets/{id}/documents
func (UnimplementedHandler) ListDocuments(ctx context.Context, params ListDocumentsParams) (r *DocumentList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMemories implements listMemories operation.
//
// GET /memories
func (UnimplementedHandler) ListMemories(ctx context.Context, params ListMemoriesParams) (r *MemoryEntryList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListModels implements listModels operation.
//
// GET /models
func (UnimplementedHandler) ListModels(ctx context.Context) (r *ModelList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListNodeTypes implements listNodeTypes operation.
//
// GET /node-types
func (UnimplementedHandler) ListNodeTypes(ctx context.Context) (r *NodeTypeList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPlugins implements listPlugins operation.
//
// GET /plugins
func (UnimplementedHandler) ListPlugins(ctx context.Context, params ListPluginsParams) (r *PluginList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProviders implements listProviders operation.
//
// GET /providers
func (UnimplementedHandler) ListProviders(ctx context.Context) (r *ProviderList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSkills implements listSkills operation.
//
// GET /skills
func (UnimplementedHandler) ListSkills(ctx context.Context) (r *SkillList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTemplates implements listTemplates operation.
//
// GET /templates
func (UnimplementedHandler) ListTemplates(ctx context.Context) (r *TemplateList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTools implements listTools operation.
//
// GET /tools
func (UnimplementedHandler) ListTools(ctx context.Context) (r *ToolList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVersions implements listVersions operation.
//
// GET /agents/{id}/versions
func (UnimplementedHandler) ListVersions(ctx context.Context, params ListVersionsParams) (r *GraphVersionList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkflowRuns implements listWorkflowRuns operation.
//
// GET /workflows/runs
func (UnimplementedHandler) ListWorkflowRuns(ctx context.Context, params ListWorkflowRunsParams) (r *WorkflowRunList, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// POST /auth/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginRequest) (r *LoginResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// POST /auth/logout
func (UnimplementedHandler) Logout(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// PublishVersion implements publishVersion operation.
//
// POST /agents/{id}/versions/publish
func (UnimplementedHandler) PublishVersion(ctx context.Context, req *PublishVersionRequest, params PublishVersionParams) (r *GraphVersion, _ error) {
	return r, ht.ErrNotImplemented
}

// QueryDocuments implements queryDocuments operation.
//
// POST /datasets/{id}/query
func (UnimplementedHandler) QueryDocuments(ctx context.Context, req *DatasetQueryRequest, params QueryDocumentsParams) (r *QueryResultList, _ error) {
	return r, ht.ErrNotImplemented
}

// ReloadPlugins implements reloadPlugins operation.
//
// POST /plugins/reload
func (UnimplementedHandler) ReloadPlugins(ctx context.Context) (r *PluginReloadResult, _ error) {
	return r, ht.ErrNotImplemented
}

// ReprocessDocument implements reprocessDocument operation.
//
// Resets processing_status to "pending" and submits the document
// to the platform's context worker. Useful for retrying a doc
// that failed during the initial generation (e.g. transient LLM
// error). Returns the patched document row.
//
// POST /datasets/{id}/documents/{docId}/reprocess
func (UnimplementedHandler) ReprocessDocument(ctx context.Context, params ReprocessDocumentParams) (r *DatasetDocument, _ error) {
	return r, ht.ErrNotImplemented
}

// RollbackVersion implements rollbackVersion operation.
//
// POST /agents/{id}/versions/{ver}/rollback
func (UnimplementedHandler) RollbackVersion(ctx context.Context, params RollbackVersionParams) (r *GraphVersion, _ error) {
	return r, ht.ErrNotImplemented
}

// SetDefaultModel implements setDefaultModel operation.
//
// PUT /models/default
func (UnimplementedHandler) SetDefaultModel(ctx context.Context, req *SetDefaultModelRequest) error {
	return ht.ErrNotImplemented
}

// SetupAuth implements setupAuth operation.
//
// One-time owner credential bootstrap. Returns 409 if already initialized.
//
// POST /auth/setup
func (UnimplementedHandler) SetupAuth(ctx context.Context, req *SetupRequest) (r *OkResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// StartConversationRun implements startConversationRun operation.
//
// Starts an agent run on this conversation. This replaces the previous
// `POST /chat/stream` SSE endpoint: the call returns immediately with the
// identifiers needed to subscribe to the resulting envelope stream.
// All token, tool-call and completion events are published to the event
// log; clients consume them via
// `GET /api/events?partition=card:{id}&since={last_seq}` (or the WS/SSE
// envelope channels exposed by the same surface).
//
// POST /conversations/{id}/runs
func (UnimplementedHandler) StartConversationRun(ctx context.Context, req *ChatRequest, params StartConversationRunParams) (r *ChatStartResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// SubmitApproval implements submitApproval operation.
//
// Submit a HITL approval decision for a paused agent run on this conversation.
// This is the command-side replacement of the deprecated `POST /chat/resume/stream`:
// the decision is injected into the saved BoardSnapshot and the agent resumes.
// The resulting envelopes (agent.stream.delta, kanban.card.*, ...) are emitted to
// the event log; subscribe to `GET /api/events?partition=card:{id}` to follow them.
//
// POST /conversations/{id}/approval
func (UnimplementedHandler) SubmitApproval(ctx context.Context, req *ApprovalDecisionRequest, params SubmitApprovalParams) (r *ApprovalDecisionResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAgent implements updateAgent operation.
//
// PUT /agents/{id}
func (UnimplementedHandler) UpdateAgent(ctx context.Context, req *UpdateAgentRequest, params UpdateAgentParams) (r *Agent, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAllSkills implements updateAllSkills operation.
//
// POST /skills/update-all
func (UnimplementedHandler) UpdateAllSkills(ctx context.Context) (r *SkillUpdateAllResult, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMemory implements updateMemory operation.
//
// PUT /memories/{entryID}
func (UnimplementedHandler) UpdateMemory(ctx context.Context, req *UpdateMemoryRequest, params UpdateMemoryParams) (r *MemoryEntry, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePluginConfig implements updatePluginConfig operation.
//
// PUT /plugins/{name}/config
func (UnimplementedHandler) UpdatePluginConfig(ctx context.Context, req PluginConfig, params UpdatePluginConfigParams) (r *PluginInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSkill implements updateSkill operation.
//
// PUT /skills/{name}
func (UnimplementedHandler) UpdateSkill(ctx context.Context, params UpdateSkillParams) (r *SkillUpdateResult, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadPlugin implements uploadPlugin operation.
//
// POST /plugins/upload
func (UnimplementedHandler) UploadPlugin(ctx context.Context, req *UploadPluginReq) (r *PluginUploadResult, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
