// Code generated by eventgen. DO NOT EDIT.

package eventlog

// AuditRequiredEventTypes lists envelope.type values that require audit_summary in contracts.
var AuditRequiredEventTypes = []string{
	EventTypeAgentRunCompleted,
	EventTypeAgentRunFailed,
	EventTypeAuditActionFailed,
	EventTypeAuditActionPerformed,
	EventTypeChatCallbackDelivered,
	EventTypeChatCallbackDismissed,
	EventTypeChatMessageSent,
	EventTypeCronRuleChanged,
	EventTypeCronRuleCreated,
	EventTypeCronRuleDisabled,
	EventTypeRealmConfigChanged,
	EventTypeRealmCreated,
	EventTypeRealmMemberAdded,
	EventTypeRealmMemberRemoved,
	EventTypeTaskCompleted,
	EventTypeTaskFailed,
	EventTypeTaskSubmitted,
	EventTypeWebhookInboundReceived,
	EventTypeWebhookOutboundExhausted,
}

// AuditSummaryTemplate returns the template from contracts or "".
func AuditSummaryTemplate(eventType string) string {
	switch eventType {
	case EventTypeAgentRunCompleted:
		return "agent run completed for card {{payload.card_id}}"
	case EventTypeAgentRunFailed:
		return "agent run failed for card {{payload.card_id}}"
	case EventTypeAuditActionFailed:
		return "audit action failed for {{payload.actor_id}}"
	case EventTypeAuditActionPerformed:
		return "audit action performed by {{payload.actor_id}}"
	case EventTypeChatCallbackDelivered:
		return "chat callback delivered for card {{payload.card_id}}"
	case EventTypeChatCallbackDismissed:
		return "chat callback dismissed for card {{payload.card_id}}"
	case EventTypeChatMessageSent:
		return "chat message sent on card {{payload.card_id}}"
	case EventTypeCronRuleChanged:
		return "cron rule {{payload.schedule_id}} changed"
	case EventTypeCronRuleCreated:
		return "cron rule {{payload.schedule_id}} created for agent {{payload.agent_id}}"
	case EventTypeCronRuleDisabled:
		return "cron rule {{payload.schedule_id}} disabled"
	case EventTypeRealmConfigChanged:
		return "realm {{payload.realm_id}} configuration changed"
	case EventTypeRealmCreated:
		return "realm {{payload.realm_id}} created"
	case EventTypeRealmMemberAdded:
		return "member added to realm {{payload.realm_id}}"
	case EventTypeRealmMemberRemoved:
		return "member removed from realm {{payload.realm_id}}"
	case EventTypeTaskCompleted:
		return "task {{payload.card_id}} completed"
	case EventTypeTaskFailed:
		return "task {{payload.card_id}} failed"
	case EventTypeTaskSubmitted:
		return "task {{payload.card_id}} submitted for agent {{payload.target_agent_id}}"
	case EventTypeWebhookInboundReceived:
		return "webhook inbound received for endpoint {{payload.endpoint_id}}"
	case EventTypeWebhookOutboundExhausted:
		return "webhook outbound exhausted for endpoint {{payload.endpoint_id}}"
	default:
		return ""
	}
}
