// Code generated by eventgen. DO NOT EDIT.

package eventlog

import (
	"context"
	"encoding/json"
	"fmt"
)

// Handler receives decoded envelope payloads. Embed DefaultHandler to opt in incrementally.
type Handler interface {
	HandleAgentRunCompleted(ctx context.Context, env Envelope, p AgentRunCompletedPayload) error
	HandleAgentRunFailed(ctx context.Context, env Envelope, p AgentRunFailedPayload) error
	HandleAgentRunStarted(ctx context.Context, env Envelope, p AgentRunStartedPayload) error
	HandleAgentStreamDelta(ctx context.Context, env Envelope, p AgentStreamDeltaPayload) error
	HandleAgentThinkingDelta(ctx context.Context, env Envelope, p AgentThinkingDeltaPayload) error
	HandleAgentToolInvoked(ctx context.Context, env Envelope, p AgentToolInvokedPayload) error
	HandleAgentToolReturned(ctx context.Context, env Envelope, p AgentToolReturnedPayload) error
	HandleAuditActionFailed(ctx context.Context, env Envelope, p AuditActionFailedPayload) error
	HandleAuditActionPerformed(ctx context.Context, env Envelope, p AuditActionPerformedPayload) error
	HandleChatCallbackDelivered(ctx context.Context, env Envelope, p ChatCallbackDeliveredPayload) error
	HandleChatCallbackDismissed(ctx context.Context, env Envelope, p ChatCallbackDismissedPayload) error
	HandleChatCallbackQueued(ctx context.Context, env Envelope, p ChatCallbackQueuedPayload) error
	HandleChatMessageSent(ctx context.Context, env Envelope, p ChatMessageSentPayload) error
	HandleCronRuleChanged(ctx context.Context, env Envelope, p CronRuleChangedPayload) error
	HandleCronRuleCreated(ctx context.Context, env Envelope, p CronRuleCreatedPayload) error
	HandleCronRuleDisabled(ctx context.Context, env Envelope, p CronRuleDisabledPayload) error
	HandleCronRuleFired(ctx context.Context, env Envelope, p CronRuleFiredPayload) error
	HandleRealmConfigChanged(ctx context.Context, env Envelope, p RealmConfigChangedPayload) error
	HandleRealmCreated(ctx context.Context, env Envelope, p RealmCreatedPayload) error
	HandleRealmMemberAdded(ctx context.Context, env Envelope, p RealmMemberAddedPayload) error
	HandleRealmMemberRemoved(ctx context.Context, env Envelope, p RealmMemberRemovedPayload) error
	HandleTaskClaimed(ctx context.Context, env Envelope, p TaskClaimedPayload) error
	HandleTaskCompleted(ctx context.Context, env Envelope, p TaskCompletedPayload) error
	HandleTaskFailed(ctx context.Context, env Envelope, p TaskFailedPayload) error
	HandleTaskSubmitted(ctx context.Context, env Envelope, p TaskSubmittedPayload) error
	HandleWebhookInboundReceived(ctx context.Context, env Envelope, p WebhookInboundBody) error
	HandleWebhookOutboundAttemptFailed(ctx context.Context, env Envelope, p WebhookOutboundAttemptFailedPayload) error
	HandleWebhookOutboundExhausted(ctx context.Context, env Envelope, p WebhookOutboundExhaustedPayload) error
	HandleWebhookOutboundQueued(ctx context.Context, env Envelope, p WebhookOutboundQueuedPayload) error
	HandleWebhookOutboundScheduled(ctx context.Context, env Envelope, p WebhookOutboundScheduledPayload) error
	HandleWebhookOutboundSent(ctx context.Context, env Envelope, p WebhookOutboundSentPayload) error
}

// DefaultHandler is a no-op Handler useful for embedding.
type DefaultHandler struct{}

func (DefaultHandler) HandleAgentRunCompleted(_ context.Context, _ Envelope, _ AgentRunCompletedPayload) error {
	return nil
}
func (DefaultHandler) HandleAgentRunFailed(_ context.Context, _ Envelope, _ AgentRunFailedPayload) error {
	return nil
}
func (DefaultHandler) HandleAgentRunStarted(_ context.Context, _ Envelope, _ AgentRunStartedPayload) error {
	return nil
}
func (DefaultHandler) HandleAgentStreamDelta(_ context.Context, _ Envelope, _ AgentStreamDeltaPayload) error {
	return nil
}
func (DefaultHandler) HandleAgentThinkingDelta(_ context.Context, _ Envelope, _ AgentThinkingDeltaPayload) error {
	return nil
}
func (DefaultHandler) HandleAgentToolInvoked(_ context.Context, _ Envelope, _ AgentToolInvokedPayload) error {
	return nil
}
func (DefaultHandler) HandleAgentToolReturned(_ context.Context, _ Envelope, _ AgentToolReturnedPayload) error {
	return nil
}
func (DefaultHandler) HandleAuditActionFailed(_ context.Context, _ Envelope, _ AuditActionFailedPayload) error {
	return nil
}
func (DefaultHandler) HandleAuditActionPerformed(_ context.Context, _ Envelope, _ AuditActionPerformedPayload) error {
	return nil
}
func (DefaultHandler) HandleChatCallbackDelivered(_ context.Context, _ Envelope, _ ChatCallbackDeliveredPayload) error {
	return nil
}
func (DefaultHandler) HandleChatCallbackDismissed(_ context.Context, _ Envelope, _ ChatCallbackDismissedPayload) error {
	return nil
}
func (DefaultHandler) HandleChatCallbackQueued(_ context.Context, _ Envelope, _ ChatCallbackQueuedPayload) error {
	return nil
}
func (DefaultHandler) HandleChatMessageSent(_ context.Context, _ Envelope, _ ChatMessageSentPayload) error {
	return nil
}
func (DefaultHandler) HandleCronRuleChanged(_ context.Context, _ Envelope, _ CronRuleChangedPayload) error {
	return nil
}
func (DefaultHandler) HandleCronRuleCreated(_ context.Context, _ Envelope, _ CronRuleCreatedPayload) error {
	return nil
}
func (DefaultHandler) HandleCronRuleDisabled(_ context.Context, _ Envelope, _ CronRuleDisabledPayload) error {
	return nil
}
func (DefaultHandler) HandleCronRuleFired(_ context.Context, _ Envelope, _ CronRuleFiredPayload) error {
	return nil
}
func (DefaultHandler) HandleRealmConfigChanged(_ context.Context, _ Envelope, _ RealmConfigChangedPayload) error {
	return nil
}
func (DefaultHandler) HandleRealmCreated(_ context.Context, _ Envelope, _ RealmCreatedPayload) error {
	return nil
}
func (DefaultHandler) HandleRealmMemberAdded(_ context.Context, _ Envelope, _ RealmMemberAddedPayload) error {
	return nil
}
func (DefaultHandler) HandleRealmMemberRemoved(_ context.Context, _ Envelope, _ RealmMemberRemovedPayload) error {
	return nil
}
func (DefaultHandler) HandleTaskClaimed(_ context.Context, _ Envelope, _ TaskClaimedPayload) error {
	return nil
}
func (DefaultHandler) HandleTaskCompleted(_ context.Context, _ Envelope, _ TaskCompletedPayload) error {
	return nil
}
func (DefaultHandler) HandleTaskFailed(_ context.Context, _ Envelope, _ TaskFailedPayload) error {
	return nil
}
func (DefaultHandler) HandleTaskSubmitted(_ context.Context, _ Envelope, _ TaskSubmittedPayload) error {
	return nil
}
func (DefaultHandler) HandleWebhookInboundReceived(_ context.Context, _ Envelope, _ WebhookInboundBody) error {
	return nil
}
func (DefaultHandler) HandleWebhookOutboundAttemptFailed(_ context.Context, _ Envelope, _ WebhookOutboundAttemptFailedPayload) error {
	return nil
}
func (DefaultHandler) HandleWebhookOutboundExhausted(_ context.Context, _ Envelope, _ WebhookOutboundExhaustedPayload) error {
	return nil
}
func (DefaultHandler) HandleWebhookOutboundQueued(_ context.Context, _ Envelope, _ WebhookOutboundQueuedPayload) error {
	return nil
}
func (DefaultHandler) HandleWebhookOutboundScheduled(_ context.Context, _ Envelope, _ WebhookOutboundScheduledPayload) error {
	return nil
}
func (DefaultHandler) HandleWebhookOutboundSent(_ context.Context, _ Envelope, _ WebhookOutboundSentPayload) error {
	return nil
}

// Dispatch routes env to the matching Handle* method on h.
func Dispatch(ctx context.Context, env Envelope, h Handler) error {
	switch env.Type {
	case EventTypeAgentRunCompleted:
		var p AgentRunCompletedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleAgentRunCompleted(ctx, env, p)
	case EventTypeAgentRunFailed:
		var p AgentRunFailedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleAgentRunFailed(ctx, env, p)
	case EventTypeAgentRunStarted:
		var p AgentRunStartedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleAgentRunStarted(ctx, env, p)
	case EventTypeAgentStreamDelta:
		var p AgentStreamDeltaPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleAgentStreamDelta(ctx, env, p)
	case EventTypeAgentThinkingDelta:
		var p AgentThinkingDeltaPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleAgentThinkingDelta(ctx, env, p)
	case EventTypeAgentToolInvoked:
		var p AgentToolInvokedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleAgentToolInvoked(ctx, env, p)
	case EventTypeAgentToolReturned:
		var p AgentToolReturnedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleAgentToolReturned(ctx, env, p)
	case EventTypeAuditActionFailed:
		var p AuditActionFailedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleAuditActionFailed(ctx, env, p)
	case EventTypeAuditActionPerformed:
		var p AuditActionPerformedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleAuditActionPerformed(ctx, env, p)
	case EventTypeChatCallbackDelivered:
		var p ChatCallbackDeliveredPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleChatCallbackDelivered(ctx, env, p)
	case EventTypeChatCallbackDismissed:
		var p ChatCallbackDismissedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleChatCallbackDismissed(ctx, env, p)
	case EventTypeChatCallbackQueued:
		var p ChatCallbackQueuedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleChatCallbackQueued(ctx, env, p)
	case EventTypeChatMessageSent:
		var p ChatMessageSentPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleChatMessageSent(ctx, env, p)
	case EventTypeCronRuleChanged:
		var p CronRuleChangedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleCronRuleChanged(ctx, env, p)
	case EventTypeCronRuleCreated:
		var p CronRuleCreatedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleCronRuleCreated(ctx, env, p)
	case EventTypeCronRuleDisabled:
		var p CronRuleDisabledPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleCronRuleDisabled(ctx, env, p)
	case EventTypeCronRuleFired:
		var p CronRuleFiredPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleCronRuleFired(ctx, env, p)
	case EventTypeRealmConfigChanged:
		var p RealmConfigChangedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleRealmConfigChanged(ctx, env, p)
	case EventTypeRealmCreated:
		var p RealmCreatedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleRealmCreated(ctx, env, p)
	case EventTypeRealmMemberAdded:
		var p RealmMemberAddedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleRealmMemberAdded(ctx, env, p)
	case EventTypeRealmMemberRemoved:
		var p RealmMemberRemovedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleRealmMemberRemoved(ctx, env, p)
	case EventTypeTaskClaimed:
		var p TaskClaimedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleTaskClaimed(ctx, env, p)
	case EventTypeTaskCompleted:
		var p TaskCompletedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleTaskCompleted(ctx, env, p)
	case EventTypeTaskFailed:
		var p TaskFailedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleTaskFailed(ctx, env, p)
	case EventTypeTaskSubmitted:
		var p TaskSubmittedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleTaskSubmitted(ctx, env, p)
	case EventTypeWebhookInboundReceived:
		var p WebhookInboundBody
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleWebhookInboundReceived(ctx, env, p)
	case EventTypeWebhookOutboundAttemptFailed:
		var p WebhookOutboundAttemptFailedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleWebhookOutboundAttemptFailed(ctx, env, p)
	case EventTypeWebhookOutboundExhausted:
		var p WebhookOutboundExhaustedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleWebhookOutboundExhausted(ctx, env, p)
	case EventTypeWebhookOutboundQueued:
		var p WebhookOutboundQueuedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleWebhookOutboundQueued(ctx, env, p)
	case EventTypeWebhookOutboundScheduled:
		var p WebhookOutboundScheduledPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleWebhookOutboundScheduled(ctx, env, p)
	case EventTypeWebhookOutboundSent:
		var p WebhookOutboundSentPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleWebhookOutboundSent(ctx, env, p)
	default:
		return fmt.Errorf("unknown event type %q", env.Type)
	}
}
