// Code generated by eventgen. DO NOT EDIT.

package eventlog

const (
	EventTypeAgentRunCompleted             = "agent.run.completed"
	EventTypeAgentRunFailed                = "agent.run.failed"
	EventTypeAgentRunStarted               = "agent.run.started"
	EventTypeAgentStreamDelta              = "agent.stream.delta"
	EventTypeAgentThinkingDelta            = "agent.thinking.delta"
	EventTypeAgentToolInvoked              = "agent.tool.invoked"
	EventTypeAgentToolReturned             = "agent.tool.returned"
	EventTypeAuditActionFailed             = "audit.action.failed"
	EventTypeAuditActionPerformed          = "audit.action.performed"
	EventTypeChatCallbackDelivered         = "chat.callback.delivered"
	EventTypeChatCallbackDismissed         = "chat.callback.dismissed"
	EventTypeChatCallbackQueued            = "chat.callback.queued"
	EventTypeChatMessageSent               = "chat.message.sent"
	EventTypeCronRuleChanged               = "cron.rule.changed"
	EventTypeCronRuleCreated               = "cron.rule.created"
	EventTypeCronRuleDisabled              = "cron.rule.disabled"
	EventTypeCronRuleFired                 = "cron.rule.fired"
	EventTypeRealmConfigChanged            = "realm.config.changed"
	EventTypeRealmCreated                  = "realm.created"
	EventTypeRealmMemberAdded              = "realm.member.added"
	EventTypeRealmMemberRemoved            = "realm.member.removed"
	EventTypeTaskClaimed                   = "task.claimed"
	EventTypeTaskCompleted                 = "task.completed"
	EventTypeTaskFailed                    = "task.failed"
	EventTypeTaskSubmitted                 = "task.submitted"
	EventTypeWebhookInboundReceived        = "webhook.inbound.received"
	EventTypeWebhookOutboundAttempt_failed = "webhook.outbound.attempt_failed"
	EventTypeWebhookOutboundExhausted      = "webhook.outbound.exhausted"
	EventTypeWebhookOutboundQueued         = "webhook.outbound.queued"
	EventTypeWebhookOutboundScheduled      = "webhook.outbound.scheduled"
	EventTypeWebhookOutboundSent           = "webhook.outbound.sent"
)

// EventTypes lists every known envelope.type value (sorted).
var EventTypes = []string{
	EventTypeAgentRunCompleted,
	EventTypeAgentRunFailed,
	EventTypeAgentRunStarted,
	EventTypeAgentStreamDelta,
	EventTypeAgentThinkingDelta,
	EventTypeAgentToolInvoked,
	EventTypeAgentToolReturned,
	EventTypeAuditActionFailed,
	EventTypeAuditActionPerformed,
	EventTypeChatCallbackDelivered,
	EventTypeChatCallbackDismissed,
	EventTypeChatCallbackQueued,
	EventTypeChatMessageSent,
	EventTypeCronRuleChanged,
	EventTypeCronRuleCreated,
	EventTypeCronRuleDisabled,
	EventTypeCronRuleFired,
	EventTypeRealmConfigChanged,
	EventTypeRealmCreated,
	EventTypeRealmMemberAdded,
	EventTypeRealmMemberRemoved,
	EventTypeTaskClaimed,
	EventTypeTaskCompleted,
	EventTypeTaskFailed,
	EventTypeTaskSubmitted,
	EventTypeWebhookInboundReceived,
	EventTypeWebhookOutboundAttempt_failed,
	EventTypeWebhookOutboundExhausted,
	EventTypeWebhookOutboundQueued,
	EventTypeWebhookOutboundScheduled,
	EventTypeWebhookOutboundSent,
}

const CategoryAudit = "audit"

const CategoryBusiness = "business"

const CategoryOperational = "operational"

const CategoryPermanent = "permanent"

const CategoryVolatile = "volatile"
