// Code generated by eventgen. DO NOT EDIT.

package eventlog

import "strings"

// PartitionRuntime builds "runtime" partitions.
func PartitionRuntime(runtimeID string) string {
	return "runtime:" + strings.TrimSpace(runtimeID)
}

// PartitionCard builds "card" partitions.
func PartitionCard(cardID string) string {
	return "card:" + strings.TrimSpace(cardID)
}

// PartitionWebhook builds "webhook_endpoint" partitions.
func PartitionWebhook(endpointID string) string {
	return "webhook:" + strings.TrimSpace(endpointID)
}

// PartitionCron builds "cron_rule" partitions.
func PartitionCron(ruleID string) string {
	return "cron:" + strings.TrimSpace(ruleID)
}

// PartitionRealm builds "realm" partitions.
func PartitionRealm(realmID string) string {
	return "realm:" + strings.TrimSpace(realmID)
}

// PartitionActor builds "actor" partitions.
func PartitionActor(actorID string) string {
	return "actor:" + strings.TrimSpace(actorID)
}
