// Code generated by eventgen. DO NOT EDIT.

package eventlog

import "encoding/json"

// AgentRunCompletedPayload is generated from contracts.
type AgentRunCompletedPayload struct {
	CardID string `json:"card_id"`
	Output string `json:"output"`
	RunID  string `json:"run_id"`
}

// AgentRunFailedPayload is generated from contracts.
type AgentRunFailedPayload struct {
	CardID string `json:"card_id"`
	Error  string `json:"error"`
	RunID  string `json:"run_id"`
}

// AgentRunStartedPayload is generated from contracts.
type AgentRunStartedPayload struct {
	CardID string `json:"card_id"`
	RunID  string `json:"run_id"`
}

// AgentStreamDeltaPayload is generated from contracts.
type AgentStreamDeltaPayload struct {
	CardID         string `json:"card_id"`
	ConversationID string `json:"conversation_id"`
	Delta          string `json:"delta"`
	DeltaSeq       int64  `json:"delta_seq"`
	Finished       bool   `json:"finished"`
	Role           string `json:"role"`
	RunID          string `json:"run_id"`
}

// AgentThinkingDeltaPayload is generated from contracts.
type AgentThinkingDeltaPayload struct {
	CardID   string `json:"card_id"`
	Delta    string `json:"delta"`
	DeltaSeq int64  `json:"delta_seq"`
	Finished bool   `json:"finished"`
	RunID    string `json:"run_id"`
}

// AgentToolInvokedPayload is generated from contracts.
type AgentToolInvokedPayload struct {
	Arguments string `json:"arguments"`
	CallID    string `json:"call_id"`
	CardID    string `json:"card_id"`
	RunID     string `json:"run_id"`
	ToolName  string `json:"tool_name"`
}

// AgentToolReturnedPayload is generated from contracts.
type AgentToolReturnedPayload struct {
	CallID     string `json:"call_id"`
	CardID     string `json:"card_id"`
	DurationMs int64  `json:"duration_ms"`
	Error      string `json:"error"`
	Output     string `json:"output"`
	RunID      string `json:"run_id"`
	Status     string `json:"status"`
	ToolName   string `json:"tool_name"`
}

// AuditActionFailedPayload is generated from contracts.
type AuditActionFailedPayload struct {
	Action       string `json:"action"`
	ActorID      string `json:"actor_id"`
	ErrorClass   string `json:"error_class"`
	ErrorMessage string `json:"error_message"`
	IPAddress    string `json:"ip_address"`
	OccurredAt   string `json:"occurred_at"`
	UserAgent    string `json:"user_agent"`
}

// AuditActionPerformedPayload is generated from contracts.
type AuditActionPerformedPayload struct {
	Action     string         `json:"action"`
	ActorID    string         `json:"actor_id"`
	Details    map[string]any `json:"details"`
	IPAddress  string         `json:"ip_address"`
	OccurredAt string         `json:"occurred_at"`
	TargetID   string         `json:"target_id"`
	TargetType string         `json:"target_type"`
	UserAgent  string         `json:"user_agent"`
}

// ChatCallbackDeliveredPayload is generated from contracts.
type ChatCallbackDeliveredPayload struct {
	CallbackID     string `json:"callback_id"`
	CardID         string `json:"card_id"`
	ConversationID string `json:"conversation_id"`
	DeliveredTo    string `json:"delivered_to"`
	Success        bool   `json:"success"`
}

// ChatCallbackDismissedPayload is generated from contracts.
type ChatCallbackDismissedPayload struct {
	CallbackID     string `json:"callback_id"`
	CardID         string `json:"card_id"`
	ConversationID string `json:"conversation_id"`
	Reason         string `json:"reason"`
}

// ChatCallbackQueuedPayload is generated from contracts.
type ChatCallbackQueuedPayload struct {
	CallbackID     string `json:"callback_id"`
	CardID         string `json:"card_id"`
	Content        string `json:"content"`
	ContentType    string `json:"content_type"`
	ConversationID string `json:"conversation_id"`
	SourceCardID   string `json:"source_card_id"`
}

// ChatMessageSentPayload is generated from contracts.
type ChatMessageSentPayload struct {
	CardID         string `json:"card_id"`
	Content        string `json:"content"`
	ConversationID string `json:"conversation_id"`
	MessageID      string `json:"message_id"`
	Role           string `json:"role"`
}

// CronRuleChangedPayload is generated from contracts.
type CronRuleChangedPayload struct {
	AgentID    string `json:"agent_id"`
	Cron       string `json:"cron"`
	Query      string `json:"query"`
	ScheduleID string `json:"schedule_id"`
	Timezone   string `json:"timezone"`
}

// CronRuleCreatedPayload is generated from contracts.
type CronRuleCreatedPayload struct {
	AgentID    string `json:"agent_id"`
	Cron       string `json:"cron"`
	Query      string `json:"query"`
	ScheduleID string `json:"schedule_id"`
	Timezone   string `json:"timezone"`
}

// CronRuleDisabledPayload is generated from contracts.
type CronRuleDisabledPayload struct {
	AgentID    string `json:"agent_id"`
	ScheduleID string `json:"schedule_id"`
}

// CronRuleFiredPayload is generated from contracts.
type CronRuleFiredPayload struct {
	AgentID    string `json:"agent_id"`
	CardID     string `json:"card_id"`
	Query      string `json:"query"`
	ScheduleID string `json:"schedule_id"`
}

// RealmConfigChangedPayload is generated from contracts.
type RealmConfigChangedPayload struct {
	Keys    []string `json:"keys"`
	RealmID string   `json:"realm_id"`
}

// RealmCreatedPayload is generated from contracts.
type RealmCreatedPayload struct {
	Name    string `json:"name"`
	RealmID string `json:"realm_id"`
}

// RealmMemberAddedPayload is generated from contracts.
type RealmMemberAddedPayload struct {
	MemberID string `json:"member_id"`
	RealmID  string `json:"realm_id"`
	Role     string `json:"role"`
}

// RealmMemberRemovedPayload is generated from contracts.
type RealmMemberRemovedPayload struct {
	MemberID string `json:"member_id"`
	RealmID  string `json:"realm_id"`
}

// TaskClaimedPayload is generated from contracts.
type TaskClaimedPayload struct {
	CardID        string `json:"card_id"`
	Consumer      string `json:"consumer"`
	RuntimeID     string `json:"runtime_id"`
	TargetAgentID string `json:"target_agent_id"`
}

// TaskCompletedPayload is generated from contracts.
type TaskCompletedPayload struct {
	CardID        string `json:"card_id"`
	ElapsedMs     int64  `json:"elapsed_ms"`
	Output        string `json:"output"`
	RuntimeID     string `json:"runtime_id"`
	TargetAgentID string `json:"target_agent_id"`
}

// TaskFailedPayload is generated from contracts.
type TaskFailedPayload struct {
	CardID        string `json:"card_id"`
	ElapsedMs     int64  `json:"elapsed_ms"`
	Error         string `json:"error"`
	RuntimeID     string `json:"runtime_id"`
	TargetAgentID string `json:"target_agent_id"`
}

// TaskSubmittedPayload is generated from contracts.
type TaskSubmittedPayload struct {
	CardID        string         `json:"card_id"`
	Inputs        map[string]any `json:"inputs"`
	Query         string         `json:"query"`
	RuntimeID     string         `json:"runtime_id"`
	TargetAgentID string         `json:"target_agent_id"`
}

// WebhookInboundBody is generated from contracts.
type WebhookInboundBody struct {
	Body        string            `json:"body"`
	ContentType string            `json:"content_type"`
	EndpointID  string            `json:"endpoint_id"`
	Headers     map[string]string `json:"headers"`
}

// WebhookOutboundAttemptFailedPayload is generated from contracts.
type WebhookOutboundAttemptFailedPayload struct {
	Attempt      int32  `json:"attempt"`
	DeliveryID   string `json:"delivery_id"`
	DurationMs   int64  `json:"duration_ms"`
	EndpointID   string `json:"endpoint_id"`
	ErrorClass   string `json:"error_class"`
	ErrorMessage string `json:"error_message"`
	StatusCode   int32  `json:"status_code"`
}

// WebhookOutboundExhaustedPayload is generated from contracts.
type WebhookOutboundExhaustedPayload struct {
	DeliveryID    string `json:"delivery_id"`
	EndpointID    string `json:"endpoint_id"`
	FinalError    string `json:"final_error"`
	TotalAttempts int32  `json:"total_attempts"`
}

// WebhookOutboundQueuedPayload is generated from contracts.
type WebhookOutboundQueuedPayload struct {
	Body             string            `json:"body"`
	DeliveryID       string            `json:"delivery_id"`
	EndpointID       string            `json:"endpoint_id"`
	Headers          map[string]string `json:"headers"`
	InitialBackoffMs int32             `json:"initial_backoff_ms"`
	MaxAttempts      int32             `json:"max_attempts"`
	Method           string            `json:"method"`
	SourceEventSeq   int64             `json:"source_event_seq"`
	URL              string            `json:"url"`
}

// WebhookOutboundScheduledPayload is generated from contracts.
type WebhookOutboundScheduledPayload struct {
	Attempt    int32  `json:"attempt"`
	DeliveryID string `json:"delivery_id"`
	EndpointID string `json:"endpoint_id"`
	NotBefore  string `json:"not_before"`
	Reason     string `json:"reason"`
}

// WebhookOutboundSentPayload is generated from contracts.
type WebhookOutboundSentPayload struct {
	Attempt      int32  `json:"attempt"`
	DeliveryID   string `json:"delivery_id"`
	DurationMs   int64  `json:"duration_ms"`
	EndpointID   string `json:"endpoint_id"`
	ResponseBody string `json:"response_body"`
	StatusCode   int32  `json:"status_code"`
}

// PayloadTypeFor returns the concrete payload struct name for an event type, or "" if unknown.
func PayloadTypeFor(eventType string) string {
	switch eventType {
	case EventTypeAgentRunCompleted:
		return "AgentRunCompletedPayload"
	case EventTypeAgentRunFailed:
		return "AgentRunFailedPayload"
	case EventTypeAgentRunStarted:
		return "AgentRunStartedPayload"
	case EventTypeAgentStreamDelta:
		return "AgentStreamDeltaPayload"
	case EventTypeAgentThinkingDelta:
		return "AgentThinkingDeltaPayload"
	case EventTypeAgentToolInvoked:
		return "AgentToolInvokedPayload"
	case EventTypeAgentToolReturned:
		return "AgentToolReturnedPayload"
	case EventTypeAuditActionFailed:
		return "AuditActionFailedPayload"
	case EventTypeAuditActionPerformed:
		return "AuditActionPerformedPayload"
	case EventTypeChatCallbackDelivered:
		return "ChatCallbackDeliveredPayload"
	case EventTypeChatCallbackDismissed:
		return "ChatCallbackDismissedPayload"
	case EventTypeChatCallbackQueued:
		return "ChatCallbackQueuedPayload"
	case EventTypeChatMessageSent:
		return "ChatMessageSentPayload"
	case EventTypeCronRuleChanged:
		return "CronRuleChangedPayload"
	case EventTypeCronRuleCreated:
		return "CronRuleCreatedPayload"
	case EventTypeCronRuleDisabled:
		return "CronRuleDisabledPayload"
	case EventTypeCronRuleFired:
		return "CronRuleFiredPayload"
	case EventTypeRealmConfigChanged:
		return "RealmConfigChangedPayload"
	case EventTypeRealmCreated:
		return "RealmCreatedPayload"
	case EventTypeRealmMemberAdded:
		return "RealmMemberAddedPayload"
	case EventTypeRealmMemberRemoved:
		return "RealmMemberRemovedPayload"
	case EventTypeTaskClaimed:
		return "TaskClaimedPayload"
	case EventTypeTaskCompleted:
		return "TaskCompletedPayload"
	case EventTypeTaskFailed:
		return "TaskFailedPayload"
	case EventTypeTaskSubmitted:
		return "TaskSubmittedPayload"
	case EventTypeWebhookInboundReceived:
		return "WebhookInboundBody"
	case EventTypeWebhookOutboundAttemptFailed:
		return "WebhookOutboundAttemptFailedPayload"
	case EventTypeWebhookOutboundExhausted:
		return "WebhookOutboundExhaustedPayload"
	case EventTypeWebhookOutboundQueued:
		return "WebhookOutboundQueuedPayload"
	case EventTypeWebhookOutboundScheduled:
		return "WebhookOutboundScheduledPayload"
	case EventTypeWebhookOutboundSent:
		return "WebhookOutboundSentPayload"
	default:
		return ""
	}
}

// UnmarshalPayload decodes env.Payload into the correct struct for env.Type.
func UnmarshalPayload(env Envelope) (any, error) {
	switch env.Type {
	case EventTypeAgentRunCompleted:
		var p AgentRunCompletedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeAgentRunFailed:
		var p AgentRunFailedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeAgentRunStarted:
		var p AgentRunStartedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeAgentStreamDelta:
		var p AgentStreamDeltaPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeAgentThinkingDelta:
		var p AgentThinkingDeltaPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeAgentToolInvoked:
		var p AgentToolInvokedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeAgentToolReturned:
		var p AgentToolReturnedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeAuditActionFailed:
		var p AuditActionFailedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeAuditActionPerformed:
		var p AuditActionPerformedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeChatCallbackDelivered:
		var p ChatCallbackDeliveredPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeChatCallbackDismissed:
		var p ChatCallbackDismissedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeChatCallbackQueued:
		var p ChatCallbackQueuedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeChatMessageSent:
		var p ChatMessageSentPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeCronRuleChanged:
		var p CronRuleChangedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeCronRuleCreated:
		var p CronRuleCreatedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeCronRuleDisabled:
		var p CronRuleDisabledPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeCronRuleFired:
		var p CronRuleFiredPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeRealmConfigChanged:
		var p RealmConfigChangedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeRealmCreated:
		var p RealmCreatedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeRealmMemberAdded:
		var p RealmMemberAddedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeRealmMemberRemoved:
		var p RealmMemberRemovedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeTaskClaimed:
		var p TaskClaimedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeTaskCompleted:
		var p TaskCompletedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeTaskFailed:
		var p TaskFailedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeTaskSubmitted:
		var p TaskSubmittedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeWebhookInboundReceived:
		var p WebhookInboundBody
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeWebhookOutboundAttemptFailed:
		var p WebhookOutboundAttemptFailedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeWebhookOutboundExhausted:
		var p WebhookOutboundExhaustedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeWebhookOutboundQueued:
		var p WebhookOutboundQueuedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeWebhookOutboundScheduled:
		var p WebhookOutboundScheduledPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	case EventTypeWebhookOutboundSent:
		var p WebhookOutboundSentPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	default:
		return nil, nil
	}
}
