// Code generated by eventgen. DO NOT EDIT.

package eventlog

import (
	"context"
	"encoding/json"
)

// PublishAgentRunCompleted appends a agent.run.completed envelope (category=business, version=1).
func PublishAgentRunCompleted(ctx context.Context, log Appender, cardID string, p AgentRunCompletedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentRunCompleted,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentRunFailed appends a agent.run.failed envelope (category=business, version=1).
func PublishAgentRunFailed(ctx context.Context, log Appender, cardID string, p AgentRunFailedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentRunFailed,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentRunStarted appends a agent.run.started envelope (category=business, version=1).
func PublishAgentRunStarted(ctx context.Context, log Appender, cardID string, p AgentRunStartedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentRunStarted,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentStreamDelta appends a agent.stream.delta envelope (category=volatile, version=1).
func PublishAgentStreamDelta(ctx context.Context, log Appender, cardID string, p AgentStreamDeltaPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentStreamDelta,
		Version:   1,
		Category:  CategoryVolatile,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentThinkingDelta appends a agent.thinking.delta envelope (category=volatile, version=1).
func PublishAgentThinkingDelta(ctx context.Context, log Appender, cardID string, p AgentThinkingDeltaPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentThinkingDelta,
		Version:   1,
		Category:  CategoryVolatile,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentToolInvoked appends a agent.tool.invoked envelope (category=business, version=1).
func PublishAgentToolInvoked(ctx context.Context, log Appender, cardID string, p AgentToolInvokedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentToolInvoked,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentToolReturned appends a agent.tool.returned envelope (category=business, version=1).
func PublishAgentToolReturned(ctx context.Context, log Appender, cardID string, p AgentToolReturnedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentToolReturned,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAuditActionFailed appends a audit.action.failed envelope (category=audit, version=1).
func PublishAuditActionFailed(ctx context.Context, log Appender, actorID string, p AuditActionFailedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionActor(actorID),
		Type:      EventTypeAuditActionFailed,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAuditActionPerformed appends a audit.action.performed envelope (category=audit, version=1).
func PublishAuditActionPerformed(ctx context.Context, log Appender, actorID string, p AuditActionPerformedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionActor(actorID),
		Type:      EventTypeAuditActionPerformed,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishChatCallbackDelivered appends a chat.callback.delivered envelope (category=business, version=1).
func PublishChatCallbackDelivered(ctx context.Context, log Appender, cardID string, p ChatCallbackDeliveredPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatCallbackDelivered,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishChatCallbackDismissed appends a chat.callback.dismissed envelope (category=business, version=1).
func PublishChatCallbackDismissed(ctx context.Context, log Appender, cardID string, p ChatCallbackDismissedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatCallbackDismissed,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishChatCallbackQueued appends a chat.callback.queued envelope (category=business, version=1).
func PublishChatCallbackQueued(ctx context.Context, log Appender, cardID string, p ChatCallbackQueuedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatCallbackQueued,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishChatMessageSent appends a chat.message.sent envelope (category=business, version=1).
func PublishChatMessageSent(ctx context.Context, log Appender, cardID string, p ChatMessageSentPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatMessageSent,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishCronRuleChanged appends a cron.rule.changed envelope (category=business, version=1).
func PublishCronRuleChanged(ctx context.Context, log Appender, runtimeID string, p CronRuleChangedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeCronRuleChanged,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishCronRuleCreated appends a cron.rule.created envelope (category=business, version=1).
func PublishCronRuleCreated(ctx context.Context, log Appender, runtimeID string, p CronRuleCreatedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeCronRuleCreated,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishCronRuleDisabled appends a cron.rule.disabled envelope (category=business, version=1).
func PublishCronRuleDisabled(ctx context.Context, log Appender, runtimeID string, p CronRuleDisabledPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeCronRuleDisabled,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishCronRuleFired appends a cron.rule.fired envelope (category=operational, version=1).
func PublishCronRuleFired(ctx context.Context, log Appender, ruleID string, p CronRuleFiredPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCron(ruleID),
		Type:      EventTypeCronRuleFired,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishRealmConfigChanged appends a realm.config.changed envelope (category=audit, version=1).
func PublishRealmConfigChanged(ctx context.Context, log Appender, realmID string, p RealmConfigChangedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmConfigChanged,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishRealmCreated appends a realm.created envelope (category=permanent, version=1).
func PublishRealmCreated(ctx context.Context, log Appender, realmID string, p RealmCreatedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmCreated,
		Version:   1,
		Category:  CategoryPermanent,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishRealmMemberAdded appends a realm.member.added envelope (category=audit, version=1).
func PublishRealmMemberAdded(ctx context.Context, log Appender, realmID string, p RealmMemberAddedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmMemberAdded,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishRealmMemberRemoved appends a realm.member.removed envelope (category=audit, version=1).
func PublishRealmMemberRemoved(ctx context.Context, log Appender, realmID string, p RealmMemberRemovedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmMemberRemoved,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishTaskClaimed appends a task.claimed envelope (category=business, version=1).
func PublishTaskClaimed(ctx context.Context, log Appender, runtimeID string, p TaskClaimedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskClaimed,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishTaskCompleted appends a task.completed envelope (category=business, version=1).
func PublishTaskCompleted(ctx context.Context, log Appender, runtimeID string, p TaskCompletedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskCompleted,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishTaskFailed appends a task.failed envelope (category=business, version=1).
func PublishTaskFailed(ctx context.Context, log Appender, runtimeID string, p TaskFailedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskFailed,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishTaskSubmitted appends a task.submitted envelope (category=business, version=1).
func PublishTaskSubmitted(ctx context.Context, log Appender, runtimeID string, p TaskSubmittedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskSubmitted,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookInboundReceived appends a webhook.inbound.received envelope (category=operational, version=1).
func PublishWebhookInboundReceived(ctx context.Context, log Appender, endpointID string, p WebhookInboundBody, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookInboundReceived,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookOutboundAttempt_failed appends a webhook.outbound.attempt_failed envelope (category=operational, version=1).
func PublishWebhookOutboundAttempt_failed(ctx context.Context, log Appender, endpointID string, p WebhookOutboundAttemptFailedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundAttempt_failed,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookOutboundExhausted appends a webhook.outbound.exhausted envelope (category=audit, version=1).
func PublishWebhookOutboundExhausted(ctx context.Context, log Appender, endpointID string, p WebhookOutboundExhaustedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundExhausted,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookOutboundQueued appends a webhook.outbound.queued envelope (category=operational, version=1).
func PublishWebhookOutboundQueued(ctx context.Context, log Appender, endpointID string, p WebhookOutboundQueuedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundQueued,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookOutboundScheduled appends a webhook.outbound.scheduled envelope (category=operational, version=1).
func PublishWebhookOutboundScheduled(ctx context.Context, log Appender, endpointID string, p WebhookOutboundScheduledPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundScheduled,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookOutboundSent appends a webhook.outbound.sent envelope (category=operational, version=1).
func PublishWebhookOutboundSent(ctx context.Context, log Appender, endpointID string, p WebhookOutboundSentPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundSent,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}
