// Code generated by eventgen. DO NOT EDIT.

package eventlog

import (
	"context"
	"encoding/json"
)

// PublishAgentRunCompleted appends a agent.run.completed envelope (category=business, version=1) outside a transaction.
func PublishAgentRunCompleted(ctx context.Context, log Appender, cardID string, p AgentRunCompletedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentRunCompleted,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentRunCompletedInTx appends a agent.run.completed envelope inside an open UnitOfWork.
func PublishAgentRunCompletedInTx(ctx context.Context, uow UnitOfWork, cardID string, p AgentRunCompletedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentRunCompleted,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishAgentRunFailed appends a agent.run.failed envelope (category=business, version=1) outside a transaction.
func PublishAgentRunFailed(ctx context.Context, log Appender, cardID string, p AgentRunFailedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentRunFailed,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentRunFailedInTx appends a agent.run.failed envelope inside an open UnitOfWork.
func PublishAgentRunFailedInTx(ctx context.Context, uow UnitOfWork, cardID string, p AgentRunFailedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentRunFailed,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishAgentRunStarted appends a agent.run.started envelope (category=business, version=1) outside a transaction.
func PublishAgentRunStarted(ctx context.Context, log Appender, cardID string, p AgentRunStartedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentRunStarted,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentRunStartedInTx appends a agent.run.started envelope inside an open UnitOfWork.
func PublishAgentRunStartedInTx(ctx context.Context, uow UnitOfWork, cardID string, p AgentRunStartedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentRunStarted,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishAgentStreamDelta appends a agent.stream.delta envelope (category=volatile, version=1) outside a transaction.
func PublishAgentStreamDelta(ctx context.Context, log Appender, cardID string, p AgentStreamDeltaPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentStreamDelta,
		Version:   1,
		Category:  CategoryVolatile,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentStreamDeltaInTx appends a agent.stream.delta envelope inside an open UnitOfWork.
func PublishAgentStreamDeltaInTx(ctx context.Context, uow UnitOfWork, cardID string, p AgentStreamDeltaPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentStreamDelta,
		Version:   1,
		Category:  CategoryVolatile,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishAgentThinkingDelta appends a agent.thinking.delta envelope (category=volatile, version=1) outside a transaction.
func PublishAgentThinkingDelta(ctx context.Context, log Appender, cardID string, p AgentThinkingDeltaPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentThinkingDelta,
		Version:   1,
		Category:  CategoryVolatile,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentThinkingDeltaInTx appends a agent.thinking.delta envelope inside an open UnitOfWork.
func PublishAgentThinkingDeltaInTx(ctx context.Context, uow UnitOfWork, cardID string, p AgentThinkingDeltaPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentThinkingDelta,
		Version:   1,
		Category:  CategoryVolatile,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishAgentToolInvoked appends a agent.tool.invoked envelope (category=business, version=1) outside a transaction.
func PublishAgentToolInvoked(ctx context.Context, log Appender, cardID string, p AgentToolInvokedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentToolInvoked,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentToolInvokedInTx appends a agent.tool.invoked envelope inside an open UnitOfWork.
func PublishAgentToolInvokedInTx(ctx context.Context, uow UnitOfWork, cardID string, p AgentToolInvokedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentToolInvoked,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishAgentToolReturned appends a agent.tool.returned envelope (category=business, version=1) outside a transaction.
func PublishAgentToolReturned(ctx context.Context, log Appender, cardID string, p AgentToolReturnedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentToolReturned,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAgentToolReturnedInTx appends a agent.tool.returned envelope inside an open UnitOfWork.
func PublishAgentToolReturnedInTx(ctx context.Context, uow UnitOfWork, cardID string, p AgentToolReturnedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeAgentToolReturned,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishAuditActionFailed appends a audit.action.failed envelope (category=audit, version=1) outside a transaction.
func PublishAuditActionFailed(ctx context.Context, log Appender, actorID string, p AuditActionFailedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionActor(actorID),
		Type:      EventTypeAuditActionFailed,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAuditActionFailedInTx appends a audit.action.failed envelope inside an open UnitOfWork.
func PublishAuditActionFailedInTx(ctx context.Context, uow UnitOfWork, actorID string, p AuditActionFailedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionActor(actorID),
		Type:      EventTypeAuditActionFailed,
		Version:   1,
		Category:  CategoryAudit,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishAuditActionPerformed appends a audit.action.performed envelope (category=audit, version=1) outside a transaction.
func PublishAuditActionPerformed(ctx context.Context, log Appender, actorID string, p AuditActionPerformedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionActor(actorID),
		Type:      EventTypeAuditActionPerformed,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishAuditActionPerformedInTx appends a audit.action.performed envelope inside an open UnitOfWork.
func PublishAuditActionPerformedInTx(ctx context.Context, uow UnitOfWork, actorID string, p AuditActionPerformedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionActor(actorID),
		Type:      EventTypeAuditActionPerformed,
		Version:   1,
		Category:  CategoryAudit,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishChatCallbackDelivered appends a chat.callback.delivered envelope (category=business, version=1) outside a transaction.
func PublishChatCallbackDelivered(ctx context.Context, log Appender, cardID string, p ChatCallbackDeliveredPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatCallbackDelivered,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishChatCallbackDeliveredInTx appends a chat.callback.delivered envelope inside an open UnitOfWork.
func PublishChatCallbackDeliveredInTx(ctx context.Context, uow UnitOfWork, cardID string, p ChatCallbackDeliveredPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatCallbackDelivered,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishChatCallbackDismissed appends a chat.callback.dismissed envelope (category=business, version=1) outside a transaction.
func PublishChatCallbackDismissed(ctx context.Context, log Appender, cardID string, p ChatCallbackDismissedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatCallbackDismissed,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishChatCallbackDismissedInTx appends a chat.callback.dismissed envelope inside an open UnitOfWork.
func PublishChatCallbackDismissedInTx(ctx context.Context, uow UnitOfWork, cardID string, p ChatCallbackDismissedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatCallbackDismissed,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishChatCallbackQueued appends a chat.callback.queued envelope (category=business, version=1) outside a transaction.
func PublishChatCallbackQueued(ctx context.Context, log Appender, cardID string, p ChatCallbackQueuedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatCallbackQueued,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishChatCallbackQueuedInTx appends a chat.callback.queued envelope inside an open UnitOfWork.
func PublishChatCallbackQueuedInTx(ctx context.Context, uow UnitOfWork, cardID string, p ChatCallbackQueuedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatCallbackQueued,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishChatMessageSent appends a chat.message.sent envelope (category=business, version=1) outside a transaction.
func PublishChatMessageSent(ctx context.Context, log Appender, cardID string, p ChatMessageSentPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatMessageSent,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishChatMessageSentInTx appends a chat.message.sent envelope inside an open UnitOfWork.
func PublishChatMessageSentInTx(ctx context.Context, uow UnitOfWork, cardID string, p ChatMessageSentPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type:      EventTypeChatMessageSent,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishCronRuleChanged appends a cron.rule.changed envelope (category=business, version=1) outside a transaction.
func PublishCronRuleChanged(ctx context.Context, log Appender, runtimeID string, p CronRuleChangedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeCronRuleChanged,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishCronRuleChangedInTx appends a cron.rule.changed envelope inside an open UnitOfWork.
func PublishCronRuleChangedInTx(ctx context.Context, uow UnitOfWork, runtimeID string, p CronRuleChangedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeCronRuleChanged,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishCronRuleCreated appends a cron.rule.created envelope (category=business, version=1) outside a transaction.
func PublishCronRuleCreated(ctx context.Context, log Appender, runtimeID string, p CronRuleCreatedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeCronRuleCreated,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishCronRuleCreatedInTx appends a cron.rule.created envelope inside an open UnitOfWork.
func PublishCronRuleCreatedInTx(ctx context.Context, uow UnitOfWork, runtimeID string, p CronRuleCreatedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeCronRuleCreated,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishCronRuleDisabled appends a cron.rule.disabled envelope (category=business, version=1) outside a transaction.
func PublishCronRuleDisabled(ctx context.Context, log Appender, runtimeID string, p CronRuleDisabledPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeCronRuleDisabled,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishCronRuleDisabledInTx appends a cron.rule.disabled envelope inside an open UnitOfWork.
func PublishCronRuleDisabledInTx(ctx context.Context, uow UnitOfWork, runtimeID string, p CronRuleDisabledPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeCronRuleDisabled,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishCronRuleFired appends a cron.rule.fired envelope (category=operational, version=1) outside a transaction.
func PublishCronRuleFired(ctx context.Context, log Appender, ruleID string, p CronRuleFiredPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCron(ruleID),
		Type:      EventTypeCronRuleFired,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishCronRuleFiredInTx appends a cron.rule.fired envelope inside an open UnitOfWork.
func PublishCronRuleFiredInTx(ctx context.Context, uow UnitOfWork, ruleID string, p CronRuleFiredPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCron(ruleID),
		Type:      EventTypeCronRuleFired,
		Version:   1,
		Category:  CategoryOperational,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishRealmConfigChanged appends a realm.config.changed envelope (category=audit, version=1) outside a transaction.
func PublishRealmConfigChanged(ctx context.Context, log Appender, realmID string, p RealmConfigChangedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmConfigChanged,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishRealmConfigChangedInTx appends a realm.config.changed envelope inside an open UnitOfWork.
func PublishRealmConfigChangedInTx(ctx context.Context, uow UnitOfWork, realmID string, p RealmConfigChangedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmConfigChanged,
		Version:   1,
		Category:  CategoryAudit,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishRealmCreated appends a realm.created envelope (category=permanent, version=1) outside a transaction.
func PublishRealmCreated(ctx context.Context, log Appender, realmID string, p RealmCreatedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmCreated,
		Version:   1,
		Category:  CategoryPermanent,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishRealmCreatedInTx appends a realm.created envelope inside an open UnitOfWork.
func PublishRealmCreatedInTx(ctx context.Context, uow UnitOfWork, realmID string, p RealmCreatedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmCreated,
		Version:   1,
		Category:  CategoryPermanent,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishRealmMemberAdded appends a realm.member.added envelope (category=audit, version=1) outside a transaction.
func PublishRealmMemberAdded(ctx context.Context, log Appender, realmID string, p RealmMemberAddedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmMemberAdded,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishRealmMemberAddedInTx appends a realm.member.added envelope inside an open UnitOfWork.
func PublishRealmMemberAddedInTx(ctx context.Context, uow UnitOfWork, realmID string, p RealmMemberAddedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmMemberAdded,
		Version:   1,
		Category:  CategoryAudit,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishRealmMemberRemoved appends a realm.member.removed envelope (category=audit, version=1) outside a transaction.
func PublishRealmMemberRemoved(ctx context.Context, log Appender, realmID string, p RealmMemberRemovedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmMemberRemoved,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishRealmMemberRemovedInTx appends a realm.member.removed envelope inside an open UnitOfWork.
func PublishRealmMemberRemovedInTx(ctx context.Context, uow UnitOfWork, realmID string, p RealmMemberRemovedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRealm(realmID),
		Type:      EventTypeRealmMemberRemoved,
		Version:   1,
		Category:  CategoryAudit,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishTaskClaimed appends a task.claimed envelope (category=business, version=1) outside a transaction.
func PublishTaskClaimed(ctx context.Context, log Appender, runtimeID string, p TaskClaimedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskClaimed,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishTaskClaimedInTx appends a task.claimed envelope inside an open UnitOfWork.
func PublishTaskClaimedInTx(ctx context.Context, uow UnitOfWork, runtimeID string, p TaskClaimedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskClaimed,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishTaskCompleted appends a task.completed envelope (category=business, version=1) outside a transaction.
func PublishTaskCompleted(ctx context.Context, log Appender, runtimeID string, p TaskCompletedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskCompleted,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishTaskCompletedInTx appends a task.completed envelope inside an open UnitOfWork.
func PublishTaskCompletedInTx(ctx context.Context, uow UnitOfWork, runtimeID string, p TaskCompletedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskCompleted,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishTaskFailed appends a task.failed envelope (category=business, version=1) outside a transaction.
func PublishTaskFailed(ctx context.Context, log Appender, runtimeID string, p TaskFailedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskFailed,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishTaskFailedInTx appends a task.failed envelope inside an open UnitOfWork.
func PublishTaskFailedInTx(ctx context.Context, uow UnitOfWork, runtimeID string, p TaskFailedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskFailed,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishTaskSubmitted appends a task.submitted envelope (category=business, version=1) outside a transaction.
func PublishTaskSubmitted(ctx context.Context, log Appender, runtimeID string, p TaskSubmittedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskSubmitted,
		Version:   1,
		Category:  CategoryBusiness,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishTaskSubmittedInTx appends a task.submitted envelope inside an open UnitOfWork.
func PublishTaskSubmittedInTx(ctx context.Context, uow UnitOfWork, runtimeID string, p TaskSubmittedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionRuntime(runtimeID),
		Type:      EventTypeTaskSubmitted,
		Version:   1,
		Category:  CategoryBusiness,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishWebhookInboundReceived appends a webhook.inbound.received envelope (category=operational, version=1) outside a transaction.
func PublishWebhookInboundReceived(ctx context.Context, log Appender, endpointID string, p WebhookInboundBody, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookInboundReceived,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookInboundReceivedInTx appends a webhook.inbound.received envelope inside an open UnitOfWork.
func PublishWebhookInboundReceivedInTx(ctx context.Context, uow UnitOfWork, endpointID string, p WebhookInboundBody, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookInboundReceived,
		Version:   1,
		Category:  CategoryOperational,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishWebhookOutboundAttemptFailed appends a webhook.outbound.attempt_failed envelope (category=operational, version=1) outside a transaction.
func PublishWebhookOutboundAttemptFailed(ctx context.Context, log Appender, endpointID string, p WebhookOutboundAttemptFailedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundAttemptFailed,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookOutboundAttemptFailedInTx appends a webhook.outbound.attempt_failed envelope inside an open UnitOfWork.
func PublishWebhookOutboundAttemptFailedInTx(ctx context.Context, uow UnitOfWork, endpointID string, p WebhookOutboundAttemptFailedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundAttemptFailed,
		Version:   1,
		Category:  CategoryOperational,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishWebhookOutboundExhausted appends a webhook.outbound.exhausted envelope (category=audit, version=1) outside a transaction.
func PublishWebhookOutboundExhausted(ctx context.Context, log Appender, endpointID string, p WebhookOutboundExhaustedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundExhausted,
		Version:   1,
		Category:  CategoryAudit,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookOutboundExhaustedInTx appends a webhook.outbound.exhausted envelope inside an open UnitOfWork.
func PublishWebhookOutboundExhaustedInTx(ctx context.Context, uow UnitOfWork, endpointID string, p WebhookOutboundExhaustedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundExhausted,
		Version:   1,
		Category:  CategoryAudit,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishWebhookOutboundQueued appends a webhook.outbound.queued envelope (category=operational, version=1) outside a transaction.
func PublishWebhookOutboundQueued(ctx context.Context, log Appender, endpointID string, p WebhookOutboundQueuedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundQueued,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookOutboundQueuedInTx appends a webhook.outbound.queued envelope inside an open UnitOfWork.
func PublishWebhookOutboundQueuedInTx(ctx context.Context, uow UnitOfWork, endpointID string, p WebhookOutboundQueuedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundQueued,
		Version:   1,
		Category:  CategoryOperational,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishWebhookOutboundScheduled appends a webhook.outbound.scheduled envelope (category=operational, version=1) outside a transaction.
func PublishWebhookOutboundScheduled(ctx context.Context, log Appender, endpointID string, p WebhookOutboundScheduledPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundScheduled,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookOutboundScheduledInTx appends a webhook.outbound.scheduled envelope inside an open UnitOfWork.
func PublishWebhookOutboundScheduledInTx(ctx context.Context, uow UnitOfWork, endpointID string, p WebhookOutboundScheduledPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundScheduled,
		Version:   1,
		Category:  CategoryOperational,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}

// PublishWebhookOutboundSent appends a webhook.outbound.sent envelope (category=operational, version=1) outside a transaction.
func PublishWebhookOutboundSent(ctx context.Context, log Appender, endpointID string, p WebhookOutboundSentPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundSent,
		Version:   1,
		Category:  CategoryOperational,
		Ts:        NowRFC3339Nano(),
		Payload:   b,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	}
	return log.Append(ctx, env)
}

// PublishWebhookOutboundSentInTx appends a webhook.outbound.sent envelope inside an open UnitOfWork.
func PublishWebhookOutboundSentInTx(ctx context.Context, uow UnitOfWork, endpointID string, p WebhookOutboundSentPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionWebhook(endpointID),
		Type:      EventTypeWebhookOutboundSent,
		Version:   1,
		Category:  CategoryOperational,
		Payload:   p,
		Actor:     o.actor,
		TraceID:   o.traceID,
		SpanID:    o.spanID,
	})
}
