SHELL := /bin/bash
.DEFAULT_GOAL := help

VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
LDFLAGS := -X main.cliVersion=$(VERSION)

OPENAPI_SPEC := internal/api/openapi.yaml

# Independent Go modules in this repo.
# Each module is treated as if checked out separately (no go.work);
# sdkx / plugin / examples consume sdk via the published version pinned in their go.mod.
GO_MODULES := . sdk sdkx plugin examples/voice-pipeline

EVENTGEN := go run ./cmd/eventgen

EVENT_GEN_FILES := \
	contracts/envelope.schema.json \
	contracts/payloads.schema.json \
	internal/eventlog/events_gen.go \
	internal/eventlog/payloads_gen.go \
	internal/eventlog/partitions_gen.go \
	internal/eventlog/dispatch_gen.go \
	internal/eventlog/publish_gen.go \
	internal/eventlog/audit_gen.go \
	web/src/api/events.gen.ts \
	web/src/api/event_payloads.gen.ts \
	web/src/api/event_guards.gen.ts

.PHONY: help
help:
	@echo "FlowCraft"
	@echo ""
	@echo "  make vet       Run go vet on all modules"
	@echo "  make test      Run tests on all modules"
	@echo "  make fmt       Run gofmt on all modules"
	@echo "  make tidy      Run go mod tidy on all modules"
	@echo "  make ci        vet + test"
	@echo "  make build     Build flowcraft binary"
	@echo "  make generate         Regenerate all code from openapi.yaml"
	@echo "  make gen-go           Regenerate Go server stubs (ogen)"
	@echo "  make gen-web          Regenerate Web TypeScript types (openapi-typescript)"
	@echo "  make verify-generated Verify generated code is in sync with openapi.yaml"
	@echo "  make events-gen      Regenerate contracts → Go/TS/JSON Schema (eventgen)"
	@echo "  make events-check    Lint contracts + evolution + drift (CI)"
	@echo "  make events-diff     Diff events vs baseline snapshot"
	@echo "  make events-fmt      Format contracts/**/*.yaml"
	@echo "  make events-fuzz     Short fuzz on event naming rules"
	@echo "  make install-hooks   Configure git to use .githooks/ (optional)"

.PHONY: vet
vet:
	@for m in $(GO_MODULES); do echo "==> vet $$m"; ( cd $$m && go vet ./... ); done

.PHONY: test
test:
	@for m in $(GO_MODULES); do echo "==> test $$m"; ( cd $$m && go test ./... -count=1 ); done

.PHONY: fmt
fmt:
	@for m in $(GO_MODULES); do echo "==> fmt $$m"; ( cd $$m && go fmt ./... ); done

.PHONY: tidy
tidy:
	@for m in $(GO_MODULES); do echo "==> tidy $$m"; ( cd $$m && go mod tidy ); done

.PHONY: build
build:
	@echo "==> build flowcraft ($(VERSION))"; go build -ldflags '$(LDFLAGS)' -o bin/flowcraft ./cmd/flowcraft

.PHONY: generate
generate: gen-go gen-web

.PHONY: gen-go
gen-go:
	@echo "==> generate Go server (ogen)"
	cd internal/api && go generate ./...

.PHONY: gen-web
gen-web:
	@echo "==> generate Web TypeScript types (openapi-typescript)"
	cd web && npx openapi-typescript ../$(OPENAPI_SPEC) -o src/api/schema.d.ts

.PHONY: verify-generated
verify-generated: generate
	@echo "==> verify generated code matches $(OPENAPI_SPEC)"
	@if ! git diff --quiet -- internal/api/oas web/src/api/schema.d.ts; then \
		echo "ERROR: generated code is out of sync with $(OPENAPI_SPEC)."; \
		echo "Run 'make generate' and commit the result."; \
		git --no-pager diff --stat -- internal/api/oas web/src/api/schema.d.ts; \
		exit 1; \
	fi
	@echo "OK: generated code is in sync."

.PHONY: events-gen
events-gen:
	@echo "==> events-gen (eventgen)"
	@$(EVENTGEN) -mode=gen -repo=.
	@gofmt -w internal/eventlog/*_gen.go

.PHONY: events-check
events-check: events-partition-lint events-marker-lint
	@echo "==> events-check"
	@$(EVENTGEN) -mode=check -repo=.
	@$(EVENTGEN) -mode=gen -repo=.
	@gofmt -w internal/eventlog/*_gen.go
	@if ! git diff --exit-code -- $(EVENT_GEN_FILES); then \
		echo "ERROR: eventgen outputs out of sync with contracts."; \
		echo "Run 'make events-gen' and commit the result."; \
		git --no-pager diff --stat -- $(EVENT_GEN_FILES); \
		exit 1; \
	fi
	@echo "OK: contracts and generated event artifacts are in sync."

.PHONY: events-marker-lint
# Verify each generated file still carries the "DO NOT EDIT" marker. Catches
# the corner case where a hand-edit happens to coincide with a regen output.
events-marker-lint:
	@for f in internal/eventlog/events_gen.go internal/eventlog/payloads_gen.go internal/eventlog/partitions_gen.go internal/eventlog/dispatch_gen.go internal/eventlog/publish_gen.go internal/eventlog/audit_gen.go web/src/api/events.gen.ts web/src/api/event_payloads.gen.ts web/src/api/event_guards.gen.ts; do \
		if [ -f $$f ] && ! head -n 1 $$f | grep -q 'Code generated by eventgen'; then \
			echo "ERROR: $$f missing 'Code generated by eventgen' marker; do not hand-edit generated files."; \
			exit 1; \
		fi; \
	done

.PHONY: events-diff
events-diff:
	@$(EVENTGEN) -mode=diff -repo=.

.PHONY: events-fmt
events-fmt:
	@$(EVENTGEN) -mode=fmt -repo=.

.PHONY: events-fuzz
events-fuzz:
	go test ./cmd/eventgen -fuzz=FuzzEventNameLint -fuzztime=5s

.PHONY: events-partition-lint
# Reject raw partition string literals (e.g. "card:%s", "runtime:1") inside
# production Go files under internal/. Test files (*_test.go) and apitest/
# fixtures may construct partitions inline; comments (lines starting with //)
# never produce code. Generated files in internal/eventlog are excluded.
events-partition-lint:
	@hits=$$(grep -RnE \
	  --include='*.go' \
	  --exclude='*_test.go' \
	  --exclude-dir=eventlog \
	  --exclude-dir=apitest \
	  --exclude-dir=projectiontest \
	  --exclude-dir=eventlogtest \
	  '"(runtime|card|webhook_endpoint|cron_rule|realm|actor):[%{A-Za-z0-9_-]' \
	  internal/ 2>/dev/null \
	  | grep -vE '^[^:]+:[0-9]+:[[:space:]]*//' || true); \
	if [ -n "$$hits" ]; then \
		echo "ERROR: raw partition string literal in internal/. Use eventlog.Partition* helpers."; \
		echo "$$hits"; \
		exit 1; \
	fi

.PHONY: install-hooks
install-hooks:
	git config core.hooksPath .githooks
	chmod +x .githooks/pre-commit

.PHONY: ci
ci: vet test events-check
