// Code generated by eventgen. DO NOT EDIT.

export interface Actor {
  id: string;
  kind: string;
  realm_id: string;
}

export interface AgentConfigChangedPayload {
  agentID: string;
  change: string;
  revision?: number;
  runtimeID: string;
}

export interface AgentRunCompletedPayload {
  cardID: string;
  output?: string;
  runID: string;
}

export interface AgentRunFailedPayload {
  cardID: string;
  error: string;
  runID: string;
}

export interface AgentRunStartedPayload {
  cardID: string;
  runID: string;
}

export interface AgentStreamDeltaPayload {
  cardID: string;
  conversationID?: string;
  delta: string;
  deltaSeq: number;
  finished?: boolean;
  role?: string;
  runID: string;
}

export interface AgentThinkingDeltaPayload {
  cardID: string;
  delta: string;
  deltaSeq: number;
  finished?: boolean;
  runID: string;
}

export interface AgentToolInvokedPayload {
  arguments?: string;
  callID: string;
  cardID: string;
  runID: string;
  toolName: string;
}

export interface AgentToolReturnedPayload {
  callID: string;
  cardID: string;
  durationMs?: number;
  error?: string;
  output?: string;
  runID: string;
  status: string;
  toolName: string;
}

export interface AuditActionFailedPayload {
  action: string;
  actorID: string;
  errorClass: string;
  errorMessage: string;
  iPAddress?: string;
  occurredAt: string;
  userAgent?: string;
}

export interface AuditActionPerformedPayload {
  action: string;
  actorID: string;
  details?: Record<string, unknown>;
  iPAddress?: string;
  occurredAt: string;
  targetID?: string;
  targetType?: string;
  userAgent?: string;
}

export interface ChatCallbackDeliveredPayload {
  callbackID: string;
  cardID: string;
  conversationID: string;
  deliveredTo: string;
  success: boolean;
}

export interface ChatCallbackDismissedPayload {
  callbackID: string;
  cardID: string;
  conversationID: string;
  reason?: string;
}

export interface ChatCallbackQueuedPayload {
  callbackID: string;
  cardID: string;
  content?: string;
  contentType: string;
  conversationID: string;
  sourceCardID?: string;
}

export interface ChatMessageSentPayload {
  cardID: string;
  content?: string;
  conversationID: string;
  messageID: string;
  role: string;
  tokenCount?: number;
}

export interface CronRuleChangedPayload {
  agentID: string;
  cron: string;
  query: string;
  scheduleID: string;
  timezone?: string;
}

export interface CronRuleCreatedPayload {
  agentID: string;
  cron: string;
  query: string;
  scheduleID: string;
  timezone?: string;
}

export interface CronRuleDisabledPayload {
  agentID: string;
  scheduleID: string;
}

export interface CronRuleFiredPayload {
  agentID: string;
  cardID: string;
  query: string;
  scheduleID: string;
}

export interface RealmConfigChangedPayload {
  keys: string[];
  realmID: string;
}

export interface RealmCreatedPayload {
  name: string;
  realmID: string;
}

export interface RealmMemberAddedPayload {
  memberID: string;
  realmID: string;
  role: string;
}

export interface RealmMemberRemovedPayload {
  memberID: string;
  realmID: string;
}

export interface TaskClaimedPayload {
  cardID: string;
  consumer: string;
  runtimeID: string;
  targetAgentID: string;
}

export interface TaskCompletedPayload {
  cardID: string;
  elapsedMs: number;
  output: string;
  runtimeID: string;
  targetAgentID: string;
}

export interface TaskFailedPayload {
  cardID: string;
  elapsedMs: number;
  error: string;
  runtimeID: string;
  targetAgentID: string;
}

export interface TaskSubmittedPayload {
  cardID: string;
  inputs?: Record<string, unknown>;
  query: string;
  runtimeID: string;
  targetAgentID: string;
}

export interface WebhookInboundBody {
  body: string;
  contentType?: string;
  endpointID: string;
  headers?: Record<string, string>;
}

export interface WebhookOutboundAttemptFailedPayload {
  attempt: number;
  deliveryID: string;
  durationMs?: number;
  endpointID: string;
  errorClass: string;
  errorMessage: string;
  statusCode?: number;
}

export interface WebhookOutboundExhaustedPayload {
  deliveryID: string;
  endpointID: string;
  finalError: string;
  totalAttempts: number;
}

export interface WebhookOutboundQueuedPayload {
  body?: string;
  deliveryID: string;
  endpointID: string;
  headers?: Record<string, string>;
  initialBackoffMs?: number;
  maxAttempts?: number;
  method: string;
  sourceEventSeq?: number;
  uRL: string;
}

export interface WebhookOutboundScheduledPayload {
  attempt: number;
  deliveryID: string;
  endpointID: string;
  notBefore: string;
  reason?: string;
}

export interface WebhookOutboundSentPayload {
  attempt: number;
  deliveryID: string;
  durationMs: number;
  endpointID: string;
  responseBody?: string;
  statusCode: number;
}

