// Code generated by eventgen. DO NOT EDIT.

export interface Actor {
  id: string;
  kind: string;
  realm_id: string;
}

export interface AgentRunCompletedPayload {
  cardID: string;
  output?: string;
  runID: string;
}

export interface AgentRunFailedPayload {
  cardID: string;
  error: string;
  runID: string;
}

export interface AgentRunStartedPayload {
  cardID: string;
  runID: string;
}

export interface AgentStreamDeltaPayload {
  cardID: string;
  delta: string;
  runID: string;
}

export interface AgentThinkingDeltaPayload {
  cardID: string;
  delta: string;
  runID: string;
}

export interface AgentToolInvokedPayload {
  callID: string;
  cardID: string;
  runID: string;
  toolName: string;
}

export interface AgentToolReturnedPayload {
  callID: string;
  cardID: string;
  error?: string;
  output?: string;
  runID: string;
  toolName: string;
}

export interface AuditActionFailedPayload {
  action: string;
  actorID: string;
  error: string;
}

export interface AuditActionPerformedPayload {
  action: string;
  actorID: string;
  resource: string;
}

export interface ChatCallbackDeliveredPayload {
  callbackID: string;
  cardID: string;
  success: boolean;
}

export interface ChatCallbackDismissedPayload {
  callbackID: string;
  cardID: string;
  reason?: string;
}

export interface ChatCallbackQueuedPayload {
  callbackID: string;
  cardID: string;
}

export interface ChatMessageSentPayload {
  cardID: string;
  messageID: string;
  role: string;
}

export interface CronRuleChangedPayload {
  agentID: string;
  cron: string;
  query: string;
  scheduleID: string;
  timezone?: string;
}

export interface CronRuleCreatedPayload {
  agentID: string;
  cron: string;
  query: string;
  scheduleID: string;
  timezone?: string;
}

export interface CronRuleDisabledPayload {
  agentID: string;
  scheduleID: string;
}

export interface CronRuleFiredPayload {
  agentID: string;
  cardID: string;
  query: string;
  scheduleID: string;
}

export interface RealmConfigChangedPayload {
  keys: string[];
  realmID: string;
}

export interface RealmCreatedPayload {
  name: string;
  realmID: string;
}

export interface RealmMemberAddedPayload {
  memberID: string;
  realmID: string;
  role: string;
}

export interface RealmMemberRemovedPayload {
  memberID: string;
  realmID: string;
}

export interface TaskClaimedPayload {
  cardID: string;
  consumer: string;
  runtimeID: string;
  targetAgentID: string;
}

export interface TaskCompletedPayload {
  cardID: string;
  elapsedMs: number;
  output: string;
  runtimeID: string;
  targetAgentID: string;
}

export interface TaskFailedPayload {
  cardID: string;
  elapsedMs: number;
  error: string;
  runtimeID: string;
  targetAgentID: string;
}

export interface TaskSubmittedPayload {
  cardID: string;
  inputs?: Record<string, unknown>;
  query: string;
  runtimeID: string;
  targetAgentID: string;
}

export interface WebhookInboundBody {
  body: string;
  contentType?: string;
  endpointID: string;
  headers?: Record<string, string>;
}

export interface WebhookOutboundAttemptFailedPayload {
  attempt: number;
  deliveryID: string;
  endpointID: string;
  error: string;
}

export interface WebhookOutboundExhaustedPayload {
  deliveryID: string;
  endpointID: string;
  lastError: string;
}

export interface WebhookOutboundQueuedPayload {
  deliveryID: string;
  endpointID: string;
}

export interface WebhookOutboundScheduledPayload {
  attempt: number;
  deliveryID: string;
  endpointID: string;
  nextAt: string;
}

export interface WebhookOutboundSentPayload {
  attempt: number;
  deliveryID: string;
  endpointID: string;
  statusCode: number;
}

