// Code generated by eventgen. DO NOT EDIT.

import type { Actor } from "./event_payloads.gen";

export type EventType =
  "agent.config.changed" |
  "agent.run.completed" |
  "agent.run.failed" |
  "agent.run.started" |
  "agent.stream.delta" |
  "agent.thinking.delta" |
  "agent.tool.invoked" |
  "agent.tool.returned" |
  "audit.action.failed" |
  "audit.action.performed" |
  "chat.callback.delivered" |
  "chat.callback.dismissed" |
  "chat.callback.queued" |
  "chat.message.sent" |
  "cron.rule.changed" |
  "cron.rule.created" |
  "cron.rule.disabled" |
  "cron.rule.fired" |
  "realm.config.changed" |
  "realm.created" |
  "realm.member.added" |
  "realm.member.removed" |
  "task.claimed" |
  "task.completed" |
  "task.failed" |
  "task.submitted" |
  "webhook.inbound.received" |
  "webhook.outbound.attempt_failed" |
  "webhook.outbound.exhausted" |
  "webhook.outbound.queued" |
  "webhook.outbound.scheduled" |
  "webhook.outbound.sent";

export interface Envelope<T extends EventType = EventType> {
  seq: number;
  partition: string;
  type: T;
  version: number;
  category: string;
  ts: string;
  payload: unknown;
  actor?: Actor;
  trace_id?: string;
  span_id?: string;
}
