// Code generated by eventgen. DO NOT EDIT.

export interface Actor {
  id: string;
  kind: string;
  realm_id: string;
}

export interface TaskSubmittedPayload {
  cardID: string;
  title: string;
}

