// Code generated by eventgen. DO NOT EDIT.

import type { Actor } from "./event_payloads.gen";

export type EventType =
  "task.submitted";

export interface Envelope<T extends EventType = EventType> {
  seq: number;
  partition: string;
  type: T;
  version: number;
  category: string;
  ts: string;
  payload: unknown;
  actor?: Actor;
  trace_id?: string;
  span_id?: string;
}
