// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostVersion     string                 `protobuf:"bytes,1,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	ProtocolVersion int32                  `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

func (x *HandshakeRequest) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PluginInfo      *PluginInfo            `protobuf:"bytes,1,opt,name=plugin_info,json=pluginInfo,proto3" json:"plugin_info,omitempty"`
	ProtocolVersion int32                  `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Tools           []*ToolSpec            `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Nodes           []*NodeSpec            `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetPluginInfo() *PluginInfo {
	if x != nil {
		return x.PluginInfo
	}
	return nil
}

func (x *HandshakeResponse) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HandshakeResponse) GetTools() []*ToolSpec {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *HandshakeResponse) GetNodes() []*NodeSpec {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{3}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{4}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{5}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{8}
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolSpec            `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ListToolsResponse) GetTools() []*ToolSpec {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecuteRequest) Reset() {
	*x = ToolExecuteRequest{}
	mi := &file_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecuteRequest) ProtoMessage() {}

func (x *ToolExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecuteRequest.ProtoReflect.Descriptor instead.
func (*ToolExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ToolExecuteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolExecuteRequest) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type ToolExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecuteResponse) Reset() {
	*x = ToolExecuteResponse{}
	mi := &file_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecuteResponse) ProtoMessage() {}

func (x *ToolExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecuteResponse.ProtoReflect.Descriptor instead.
func (*ToolExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ToolExecuteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{12}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeSpec            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ListNodesResponse) GetNodes() []*NodeSpec {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// NodeMessage is the bidirectional streaming message for node execution.
// The host sends ExecuteRequest, the plugin may send callbacks (GetVar,
// SetVar, LLMGenerate, ToolExecute, StreamEmit, SandboxExec, Signal),
// and finally the plugin sends ExecuteResponse.
type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*NodeMessage_ExecuteRequest
	//	*NodeMessage_ExecuteResponse
	//	*NodeMessage_GetVarRequest
	//	*NodeMessage_GetVarResponse
	//	*NodeMessage_SetVarRequest
	//	*NodeMessage_LlmGenerateRequest
	//	*NodeMessage_LlmGenerateResponse
	//	*NodeMessage_ToolExecuteRequest
	//	*NodeMessage_ToolExecuteResponse
	//	*NodeMessage_StreamEmitRequest
	//	*NodeMessage_SandboxExecRequest
	//	*NodeMessage_SandboxExecResponse
	//	*NodeMessage_SignalRequest
	//	*NodeMessage_SignalResponse
	Msg           isNodeMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_proto_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *NodeMessage) GetMsg() isNodeMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *NodeMessage) GetExecuteRequest() *NodeExecuteRequest {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_ExecuteRequest); ok {
			return x.ExecuteRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetExecuteResponse() *NodeExecuteResponse {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_ExecuteResponse); ok {
			return x.ExecuteResponse
		}
	}
	return nil
}

func (x *NodeMessage) GetGetVarRequest() *GetVarRequest {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_GetVarRequest); ok {
			return x.GetVarRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetGetVarResponse() *GetVarResponse {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_GetVarResponse); ok {
			return x.GetVarResponse
		}
	}
	return nil
}

func (x *NodeMessage) GetSetVarRequest() *SetVarRequest {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_SetVarRequest); ok {
			return x.SetVarRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetLlmGenerateRequest() *LLMGenerateRequest {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_LlmGenerateRequest); ok {
			return x.LlmGenerateRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetLlmGenerateResponse() *LLMGenerateResponse {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_LlmGenerateResponse); ok {
			return x.LlmGenerateResponse
		}
	}
	return nil
}

func (x *NodeMessage) GetToolExecuteRequest() *ToolExecuteRequest {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_ToolExecuteRequest); ok {
			return x.ToolExecuteRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetToolExecuteResponse() *ToolExecuteResponse {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_ToolExecuteResponse); ok {
			return x.ToolExecuteResponse
		}
	}
	return nil
}

func (x *NodeMessage) GetStreamEmitRequest() *StreamEmitRequest {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_StreamEmitRequest); ok {
			return x.StreamEmitRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetSandboxExecRequest() *SandboxExecRequest {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_SandboxExecRequest); ok {
			return x.SandboxExecRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetSandboxExecResponse() *SandboxExecResponse {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_SandboxExecResponse); ok {
			return x.SandboxExecResponse
		}
	}
	return nil
}

func (x *NodeMessage) GetSignalRequest() *SignalRequest {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_SignalRequest); ok {
			return x.SignalRequest
		}
	}
	return nil
}

func (x *NodeMessage) GetSignalResponse() *SignalResponse {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_SignalResponse); ok {
			return x.SignalResponse
		}
	}
	return nil
}

type isNodeMessage_Msg interface {
	isNodeMessage_Msg()
}

type NodeMessage_ExecuteRequest struct {
	ExecuteRequest *NodeExecuteRequest `protobuf:"bytes,1,opt,name=execute_request,json=executeRequest,proto3,oneof"`
}

type NodeMessage_ExecuteResponse struct {
	ExecuteResponse *NodeExecuteResponse `protobuf:"bytes,2,opt,name=execute_response,json=executeResponse,proto3,oneof"`
}

type NodeMessage_GetVarRequest struct {
	GetVarRequest *GetVarRequest `protobuf:"bytes,3,opt,name=get_var_request,json=getVarRequest,proto3,oneof"`
}

type NodeMessage_GetVarResponse struct {
	GetVarResponse *GetVarResponse `protobuf:"bytes,4,opt,name=get_var_response,json=getVarResponse,proto3,oneof"`
}

type NodeMessage_SetVarRequest struct {
	SetVarRequest *SetVarRequest `protobuf:"bytes,5,opt,name=set_var_request,json=setVarRequest,proto3,oneof"`
}

type NodeMessage_LlmGenerateRequest struct {
	LlmGenerateRequest *LLMGenerateRequest `protobuf:"bytes,6,opt,name=llm_generate_request,json=llmGenerateRequest,proto3,oneof"`
}

type NodeMessage_LlmGenerateResponse struct {
	LlmGenerateResponse *LLMGenerateResponse `protobuf:"bytes,7,opt,name=llm_generate_response,json=llmGenerateResponse,proto3,oneof"`
}

type NodeMessage_ToolExecuteRequest struct {
	ToolExecuteRequest *ToolExecuteRequest `protobuf:"bytes,8,opt,name=tool_execute_request,json=toolExecuteRequest,proto3,oneof"`
}

type NodeMessage_ToolExecuteResponse struct {
	ToolExecuteResponse *ToolExecuteResponse `protobuf:"bytes,9,opt,name=tool_execute_response,json=toolExecuteResponse,proto3,oneof"`
}

type NodeMessage_StreamEmitRequest struct {
	StreamEmitRequest *StreamEmitRequest `protobuf:"bytes,10,opt,name=stream_emit_request,json=streamEmitRequest,proto3,oneof"`
}

type NodeMessage_SandboxExecRequest struct {
	SandboxExecRequest *SandboxExecRequest `protobuf:"bytes,11,opt,name=sandbox_exec_request,json=sandboxExecRequest,proto3,oneof"`
}

type NodeMessage_SandboxExecResponse struct {
	SandboxExecResponse *SandboxExecResponse `protobuf:"bytes,12,opt,name=sandbox_exec_response,json=sandboxExecResponse,proto3,oneof"`
}

type NodeMessage_SignalRequest struct {
	SignalRequest *SignalRequest `protobuf:"bytes,13,opt,name=signal_request,json=signalRequest,proto3,oneof"`
}

type NodeMessage_SignalResponse struct {
	SignalResponse *SignalResponse `protobuf:"bytes,14,opt,name=signal_response,json=signalResponse,proto3,oneof"`
}

func (*NodeMessage_ExecuteRequest) isNodeMessage_Msg() {}

func (*NodeMessage_ExecuteResponse) isNodeMessage_Msg() {}

func (*NodeMessage_GetVarRequest) isNodeMessage_Msg() {}

func (*NodeMessage_GetVarResponse) isNodeMessage_Msg() {}

func (*NodeMessage_SetVarRequest) isNodeMessage_Msg() {}

func (*NodeMessage_LlmGenerateRequest) isNodeMessage_Msg() {}

func (*NodeMessage_LlmGenerateResponse) isNodeMessage_Msg() {}

func (*NodeMessage_ToolExecuteRequest) isNodeMessage_Msg() {}

func (*NodeMessage_ToolExecuteResponse) isNodeMessage_Msg() {}

func (*NodeMessage_StreamEmitRequest) isNodeMessage_Msg() {}

func (*NodeMessage_SandboxExecRequest) isNodeMessage_Msg() {}

func (*NodeMessage_SandboxExecResponse) isNodeMessage_Msg() {}

func (*NodeMessage_SignalRequest) isNodeMessage_Msg() {}

func (*NodeMessage_SignalResponse) isNodeMessage_Msg() {}

type NodeExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeExecuteRequest) Reset() {
	*x = NodeExecuteRequest{}
	mi := &file_proto_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeExecuteRequest) ProtoMessage() {}

func (x *NodeExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeExecuteRequest.ProtoReflect.Descriptor instead.
func (*NodeExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *NodeExecuteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeExecuteRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type NodeExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       map[string]string      `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeExecuteResponse) Reset() {
	*x = NodeExecuteResponse{}
	mi := &file_proto_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeExecuteResponse) ProtoMessage() {}

func (x *NodeExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeExecuteResponse.ProtoReflect.Descriptor instead.
func (*NodeExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *NodeExecuteResponse) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *NodeExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetVarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVarRequest) Reset() {
	*x = GetVarRequest{}
	mi := &file_proto_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVarRequest) ProtoMessage() {}

func (x *GetVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVarRequest.ProtoReflect.Descriptor instead.
func (*GetVarRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *GetVarRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetVarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVarResponse) Reset() {
	*x = GetVarResponse{}
	mi := &file_proto_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVarResponse) ProtoMessage() {}

func (x *GetVarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVarResponse.ProtoReflect.Descriptor instead.
func (*GetVarResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *GetVarResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetVarResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SetVarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVarRequest) Reset() {
	*x = SetVarRequest{}
	mi := &file_proto_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVarRequest) ProtoMessage() {}

func (x *SetVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVarRequest.ProtoReflect.Descriptor instead.
func (*SetVarRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *SetVarRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetVarRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LLMGenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMGenerateRequest) Reset() {
	*x = LLMGenerateRequest{}
	mi := &file_proto_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMGenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMGenerateRequest) ProtoMessage() {}

func (x *LLMGenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMGenerateRequest.ProtoReflect.Descriptor instead.
func (*LLMGenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *LLMGenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type LLMGenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMGenerateResponse) Reset() {
	*x = LLMGenerateResponse{}
	mi := &file_proto_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMGenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMGenerateResponse) ProtoMessage() {}

func (x *LLMGenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMGenerateResponse.ProtoReflect.Descriptor instead.
func (*LLMGenerateResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *LLMGenerateResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *LLMGenerateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamEmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEmitRequest) Reset() {
	*x = StreamEmitRequest{}
	mi := &file_proto_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEmitRequest) ProtoMessage() {}

func (x *StreamEmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEmitRequest.ProtoReflect.Descriptor instead.
func (*StreamEmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *StreamEmitRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SandboxExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxExecRequest) Reset() {
	*x = SandboxExecRequest{}
	mi := &file_proto_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxExecRequest) ProtoMessage() {}

func (x *SandboxExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxExecRequest.ProtoReflect.Descriptor instead.
func (*SandboxExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *SandboxExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type SandboxExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxExecResponse) Reset() {
	*x = SandboxExecResponse{}
	mi := &file_proto_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxExecResponse) ProtoMessage() {}

func (x *SandboxExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxExecResponse.ProtoReflect.Descriptor instead.
func (*SandboxExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *SandboxExecResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *SandboxExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalType    string                 `protobuf:"bytes,1,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_proto_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *SignalRequest) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *SignalRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_proto_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *SignalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	Builtin       bool                   `protobuf:"varint,7,opt,name=builtin,proto3" json:"builtin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_proto_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetBuiltin() bool {
	if x != nil {
		return x.Builtin
	}
	return false
}

type ToolSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchemaJson string                 `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolSpec) Reset() {
	*x = ToolSpec{}
	mi := &file_proto_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSpec) ProtoMessage() {}

func (x *ToolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSpec.ProtoReflect.Descriptor instead.
func (*ToolSpec) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *ToolSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSpec) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

type NodeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSpec) Reset() {
	*x = NodeSpec{}
	mi := &file_proto_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSpec) ProtoMessage() {}

func (x *NodeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSpec.ProtoReflect.Descriptor instead.
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *NodeSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeSpec) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

var File_proto_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x12proto/plugin.proto\x12\x06plugin\"`\n" +
	"\x10HandshakeRequest\x12!\n" +
	"\fhost_version\x18\x01 \x01(\tR\vhostVersion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\x05R\x0fprotocolVersion\"\xc3\x01\n" +
	"\x11HandshakeResponse\x123\n" +
	"\vplugin_info\x18\x01 \x01(\v2\x12.plugin.PluginInfoR\n" +
	"pluginInfo\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\x05R\x0fprotocolVersion\x12&\n" +
	"\x05tools\x18\x03 \x03(\v2\x10.plugin.ToolSpecR\x05tools\x12&\n" +
	"\x05nodes\x18\x04 \x03(\v2\x10.plugin.NodeSpecR\x05nodes\"\x8d\x01\n" +
	"\x11InitializeRequest\x12=\n" +
	"\x06config\x18\x01 \x03(\v2%.plugin.InitializeRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12InitializeResponse\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x14\n" +
	"\x12HealthCheckRequest\"/\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\"\x12\n" +
	"\x10ListToolsRequest\";\n" +
	"\x11ListToolsResponse\x12&\n" +
	"\x05tools\x18\x01 \x03(\v2\x10.plugin.ToolSpecR\x05tools\"F\n" +
	"\x12ToolExecuteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"C\n" +
	"\x13ToolExecuteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x12\n" +
	"\x10ListNodesRequest\";\n" +
	"\x11ListNodesResponse\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.plugin.NodeSpecR\x05nodes\"\xa4\b\n" +
	"\vNodeMessage\x12E\n" +
	"\x0fexecute_request\x18\x01 \x01(\v2\x1a.plugin.NodeExecuteRequestH\x00R\x0eexecuteRequest\x12H\n" +
	"\x10execute_response\x18\x02 \x01(\v2\x1b.plugin.NodeExecuteResponseH\x00R\x0fexecuteResponse\x12?\n" +
	"\x0fget_var_request\x18\x03 \x01(\v2\x15.plugin.GetVarRequestH\x00R\rgetVarRequest\x12B\n" +
	"\x10get_var_response\x18\x04 \x01(\v2\x16.plugin.GetVarResponseH\x00R\x0egetVarResponse\x12?\n" +
	"\x0fset_var_request\x18\x05 \x01(\v2\x15.plugin.SetVarRequestH\x00R\rsetVarRequest\x12N\n" +
	"\x14llm_generate_request\x18\x06 \x01(\v2\x1a.plugin.LLMGenerateRequestH\x00R\x12llmGenerateRequest\x12Q\n" +
	"\x15llm_generate_response\x18\a \x01(\v2\x1b.plugin.LLMGenerateResponseH\x00R\x13llmGenerateResponse\x12N\n" +
	"\x14tool_execute_request\x18\b \x01(\v2\x1a.plugin.ToolExecuteRequestH\x00R\x12toolExecuteRequest\x12Q\n" +
	"\x15tool_execute_response\x18\t \x01(\v2\x1b.plugin.ToolExecuteResponseH\x00R\x13toolExecuteResponse\x12K\n" +
	"\x13stream_emit_request\x18\n" +
	" \x01(\v2\x19.plugin.StreamEmitRequestH\x00R\x11streamEmitRequest\x12N\n" +
	"\x14sandbox_exec_request\x18\v \x01(\v2\x1a.plugin.SandboxExecRequestH\x00R\x12sandboxExecRequest\x12Q\n" +
	"\x15sandbox_exec_response\x18\f \x01(\v2\x1b.plugin.SandboxExecResponseH\x00R\x13sandboxExecResponse\x12>\n" +
	"\x0esignal_request\x18\r \x01(\v2\x15.plugin.SignalRequestH\x00R\rsignalRequest\x12A\n" +
	"\x0fsignal_response\x18\x0e \x01(\v2\x16.plugin.SignalResponseH\x00R\x0esignalResponseB\x05\n" +
	"\x03msg\"\xa8\x01\n" +
	"\x12NodeExecuteRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12>\n" +
	"\x06config\x18\x02 \x03(\v2&.plugin.NodeExecuteRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\x13NodeExecuteResponse\x12B\n" +
	"\aoutputs\x18\x01 \x03(\v2(.plugin.NodeExecuteResponse.OutputsEntryR\aoutputs\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\rGetVarRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"<\n" +
	"\x0eGetVarResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"7\n" +
	"\rSetVarRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\",\n" +
	"\x12LLMGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"C\n" +
	"\x13LLMGenerateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"'\n" +
	"\x11StreamEmitRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\".\n" +
	"\x12SandboxExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"C\n" +
	"\x13SandboxExecResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"J\n" +
	"\rSignalRequest\x12\x1f\n" +
	"\vsignal_type\x18\x01 \x01(\tR\n" +
	"signalType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"&\n" +
	"\x0eSignalResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xb2\x01\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12\x18\n" +
	"\abuiltin\x18\a \x01(\bR\abuiltin\"l\n" +
	"\bToolSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\tR\x0finputSchemaJson\"?\n" +
	"\bNodeSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vschema_json\x18\x02 \x01(\tR\n" +
	"schemaJson2\x9f\x02\n" +
	"\x0fPluginLifecycle\x12@\n" +
	"\tHandshake\x12\x18.plugin.HandshakeRequest\x1a\x19.plugin.HandshakeResponse\x12C\n" +
	"\n" +
	"Initialize\x12\x19.plugin.InitializeRequest\x1a\x1a.plugin.InitializeResponse\x12=\n" +
	"\bShutdown\x12\x17.plugin.ShutdownRequest\x1a\x18.plugin.ShutdownResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.plugin.HealthCheckRequest\x1a\x1b.plugin.HealthCheckResponse2\x93\x01\n" +
	"\vToolService\x12@\n" +
	"\tListTools\x12\x18.plugin.ListToolsRequest\x1a\x19.plugin.ListToolsResponse\x12B\n" +
	"\aExecute\x12\x1a.plugin.ToolExecuteRequest\x1a\x1b.plugin.ToolExecuteResponse2\x88\x01\n" +
	"\vNodeService\x12@\n" +
	"\tListNodes\x12\x18.plugin.ListNodesRequest\x1a\x19.plugin.ListNodesResponse\x127\n" +
	"\aExecute\x12\x13.plugin.NodeMessage\x1a\x13.plugin.NodeMessage(\x010\x01B+Z)github.com/GizClaw/flowcraft/plugin/protob\x06proto3"

var (
	file_proto_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_proto_rawDescData []byte
)

func file_proto_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_proto_rawDescData
}

var file_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_plugin_proto_goTypes = []any{
	(*HandshakeRequest)(nil),    // 0: plugin.HandshakeRequest
	(*HandshakeResponse)(nil),   // 1: plugin.HandshakeResponse
	(*InitializeRequest)(nil),   // 2: plugin.InitializeRequest
	(*InitializeResponse)(nil),  // 3: plugin.InitializeResponse
	(*ShutdownRequest)(nil),     // 4: plugin.ShutdownRequest
	(*ShutdownResponse)(nil),    // 5: plugin.ShutdownResponse
	(*HealthCheckRequest)(nil),  // 6: plugin.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 7: plugin.HealthCheckResponse
	(*ListToolsRequest)(nil),    // 8: plugin.ListToolsRequest
	(*ListToolsResponse)(nil),   // 9: plugin.ListToolsResponse
	(*ToolExecuteRequest)(nil),  // 10: plugin.ToolExecuteRequest
	(*ToolExecuteResponse)(nil), // 11: plugin.ToolExecuteResponse
	(*ListNodesRequest)(nil),    // 12: plugin.ListNodesRequest
	(*ListNodesResponse)(nil),   // 13: plugin.ListNodesResponse
	(*NodeMessage)(nil),         // 14: plugin.NodeMessage
	(*NodeExecuteRequest)(nil),  // 15: plugin.NodeExecuteRequest
	(*NodeExecuteResponse)(nil), // 16: plugin.NodeExecuteResponse
	(*GetVarRequest)(nil),       // 17: plugin.GetVarRequest
	(*GetVarResponse)(nil),      // 18: plugin.GetVarResponse
	(*SetVarRequest)(nil),       // 19: plugin.SetVarRequest
	(*LLMGenerateRequest)(nil),  // 20: plugin.LLMGenerateRequest
	(*LLMGenerateResponse)(nil), // 21: plugin.LLMGenerateResponse
	(*StreamEmitRequest)(nil),   // 22: plugin.StreamEmitRequest
	(*SandboxExecRequest)(nil),  // 23: plugin.SandboxExecRequest
	(*SandboxExecResponse)(nil), // 24: plugin.SandboxExecResponse
	(*SignalRequest)(nil),       // 25: plugin.SignalRequest
	(*SignalResponse)(nil),      // 26: plugin.SignalResponse
	(*PluginInfo)(nil),          // 27: plugin.PluginInfo
	(*ToolSpec)(nil),            // 28: plugin.ToolSpec
	(*NodeSpec)(nil),            // 29: plugin.NodeSpec
	nil,                         // 30: plugin.InitializeRequest.ConfigEntry
	nil,                         // 31: plugin.NodeExecuteRequest.ConfigEntry
	nil,                         // 32: plugin.NodeExecuteResponse.OutputsEntry
}
var file_proto_plugin_proto_depIdxs = []int32{
	27, // 0: plugin.HandshakeResponse.plugin_info:type_name -> plugin.PluginInfo
	28, // 1: plugin.HandshakeResponse.tools:type_name -> plugin.ToolSpec
	29, // 2: plugin.HandshakeResponse.nodes:type_name -> plugin.NodeSpec
	30, // 3: plugin.InitializeRequest.config:type_name -> plugin.InitializeRequest.ConfigEntry
	28, // 4: plugin.ListToolsResponse.tools:type_name -> plugin.ToolSpec
	29, // 5: plugin.ListNodesResponse.nodes:type_name -> plugin.NodeSpec
	15, // 6: plugin.NodeMessage.execute_request:type_name -> plugin.NodeExecuteRequest
	16, // 7: plugin.NodeMessage.execute_response:type_name -> plugin.NodeExecuteResponse
	17, // 8: plugin.NodeMessage.get_var_request:type_name -> plugin.GetVarRequest
	18, // 9: plugin.NodeMessage.get_var_response:type_name -> plugin.GetVarResponse
	19, // 10: plugin.NodeMessage.set_var_request:type_name -> plugin.SetVarRequest
	20, // 11: plugin.NodeMessage.llm_generate_request:type_name -> plugin.LLMGenerateRequest
	21, // 12: plugin.NodeMessage.llm_generate_response:type_name -> plugin.LLMGenerateResponse
	10, // 13: plugin.NodeMessage.tool_execute_request:type_name -> plugin.ToolExecuteRequest
	11, // 14: plugin.NodeMessage.tool_execute_response:type_name -> plugin.ToolExecuteResponse
	22, // 15: plugin.NodeMessage.stream_emit_request:type_name -> plugin.StreamEmitRequest
	23, // 16: plugin.NodeMessage.sandbox_exec_request:type_name -> plugin.SandboxExecRequest
	24, // 17: plugin.NodeMessage.sandbox_exec_response:type_name -> plugin.SandboxExecResponse
	25, // 18: plugin.NodeMessage.signal_request:type_name -> plugin.SignalRequest
	26, // 19: plugin.NodeMessage.signal_response:type_name -> plugin.SignalResponse
	31, // 20: plugin.NodeExecuteRequest.config:type_name -> plugin.NodeExecuteRequest.ConfigEntry
	32, // 21: plugin.NodeExecuteResponse.outputs:type_name -> plugin.NodeExecuteResponse.OutputsEntry
	0,  // 22: plugin.PluginLifecycle.Handshake:input_type -> plugin.HandshakeRequest
	2,  // 23: plugin.PluginLifecycle.Initialize:input_type -> plugin.InitializeRequest
	4,  // 24: plugin.PluginLifecycle.Shutdown:input_type -> plugin.ShutdownRequest
	6,  // 25: plugin.PluginLifecycle.HealthCheck:input_type -> plugin.HealthCheckRequest
	8,  // 26: plugin.ToolService.ListTools:input_type -> plugin.ListToolsRequest
	10, // 27: plugin.ToolService.Execute:input_type -> plugin.ToolExecuteRequest
	12, // 28: plugin.NodeService.ListNodes:input_type -> plugin.ListNodesRequest
	14, // 29: plugin.NodeService.Execute:input_type -> plugin.NodeMessage
	1,  // 30: plugin.PluginLifecycle.Handshake:output_type -> plugin.HandshakeResponse
	3,  // 31: plugin.PluginLifecycle.Initialize:output_type -> plugin.InitializeResponse
	5,  // 32: plugin.PluginLifecycle.Shutdown:output_type -> plugin.ShutdownResponse
	7,  // 33: plugin.PluginLifecycle.HealthCheck:output_type -> plugin.HealthCheckResponse
	9,  // 34: plugin.ToolService.ListTools:output_type -> plugin.ListToolsResponse
	11, // 35: plugin.ToolService.Execute:output_type -> plugin.ToolExecuteResponse
	13, // 36: plugin.NodeService.ListNodes:output_type -> plugin.ListNodesResponse
	14, // 37: plugin.NodeService.Execute:output_type -> plugin.NodeMessage
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_plugin_proto_init() }
func file_proto_plugin_proto_init() {
	if File_proto_plugin_proto != nil {
		return
	}
	file_proto_plugin_proto_msgTypes[14].OneofWrappers = []any{
		(*NodeMessage_ExecuteRequest)(nil),
		(*NodeMessage_ExecuteResponse)(nil),
		(*NodeMessage_GetVarRequest)(nil),
		(*NodeMessage_GetVarResponse)(nil),
		(*NodeMessage_SetVarRequest)(nil),
		(*NodeMessage_LlmGenerateRequest)(nil),
		(*NodeMessage_LlmGenerateResponse)(nil),
		(*NodeMessage_ToolExecuteRequest)(nil),
		(*NodeMessage_ToolExecuteResponse)(nil),
		(*NodeMessage_StreamEmitRequest)(nil),
		(*NodeMessage_SandboxExecRequest)(nil),
		(*NodeMessage_SandboxExecResponse)(nil),
		(*NodeMessage_SignalRequest)(nil),
		(*NodeMessage_SignalResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_proto = out.File
	file_proto_plugin_proto_goTypes = nil
	file_proto_plugin_proto_depIdxs = nil
}
