package chat

import (
	"context"
	"time"

	"github.com/GizClaw/flowcraft/internal/eventlog"
	"github.com/GizClaw/flowcraft/internal/policy"
)

// CallbackEnqueueReq is the request for ChatCallbackEnqueueCommand.
type CallbackEnqueueReq struct {
	ConversationID string
	CardID         string
	SourceCardID   string
	ContentType    string // text / tool_result / status_update / error
	Content        string
	CallbackID     string // typically generated by caller; reused as command id for dedup
}

// ChatCallbackEnqueueCommand emits chat.callback.queued events. It is the
// canonical entry point invoked by the agent executor / tool dispatcher when
// a downstream sub-card produces a result that needs the originating user's
// attention.
type ChatCallbackEnqueueCommand struct {
	log eventlog.Log
}

// NewChatCallbackEnqueueCommand constructs the command.
func NewChatCallbackEnqueueCommand(log eventlog.Log) *ChatCallbackEnqueueCommand {
	return &ChatCallbackEnqueueCommand{log: log}
}

// Handle publishes a chat.callback.queued event idempotently. Caller is
// expected to be a system or agent actor (D.14: user actors are denied).
func (c *ChatCallbackEnqueueCommand) Handle(ctx context.Context, req CallbackEnqueueReq) (callbackID string, err error) {
	if req.CallbackID == "" {
		req.CallbackID = newCommandID()
	}
	if req.CardID == "" {
		req.CardID = req.ConversationID
	}
	if req.ContentType == "" {
		req.ContentType = "text"
	}
	actor, _ := policy.ActorFrom(ctx)
	now := time.Now().UTC()
	_, err = c.log.Atomic(ctx, func(uow eventlog.UnitOfWork) error {
		if dup, err := isDuplicateCommand(ctx, uow, req.CallbackID); err != nil {
			return err
		} else if dup {
			return nil
		}
		if _, err := uow.BusinessExec(ctx,
			`INSERT INTO command_dedup(command_id, executed_at) VALUES(?, ?)`,
			req.CallbackID, now.Format(time.RFC3339Nano)); err != nil {
			return err
		}
		return eventlog.PublishChatCallbackQueuedInTx(ctx, uow, req.CardID, eventlog.ChatCallbackQueuedPayload{
			CardID:         req.CardID,
			ConversationID: req.ConversationID,
			CallbackID:     req.CallbackID,
			SourceCardID:   req.SourceCardID,
			ContentType:    req.ContentType,
			Content:        req.Content,
		}, eventlog.WithActor(actorOrAnonymous(actor)))
	})
	return req.CallbackID, err
}
