// Code generated by eventgen. DO NOT EDIT.

package eventlog

// AuditRequiredEventTypes lists envelope.type values that require audit_summary in contracts.
var AuditRequiredEventTypes = []string{
}

// AuditSummaryTemplate returns the template from contracts or "".
func AuditSummaryTemplate(eventType string) string {
	switch eventType {
	default:
		return ""
	}
}
