// Code generated by eventgen. DO NOT EDIT.

package eventlog

import (
	"context"
	"encoding/json"
	"fmt"
)

// Handler receives decoded envelope payloads. Embed DefaultHandler to opt in incrementally.
type Handler interface {
	HandleTaskSubmitted(ctx context.Context, env Envelope, p TaskSubmittedPayload) error
}

// DefaultHandler is a no-op Handler useful for embedding.
type DefaultHandler struct{}

func (DefaultHandler) HandleTaskSubmitted(_ context.Context, _ Envelope, _ TaskSubmittedPayload) error { return nil }

// Dispatch routes env to the matching Handle* method on h.
func Dispatch(ctx context.Context, env Envelope, h Handler) error {
	switch env.Type {
	case EventTypeTaskSubmitted:
		var p TaskSubmittedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return err
		}
		return h.HandleTaskSubmitted(ctx, env, p)
	default:
		return fmt.Errorf("unknown event type %q", env.Type)
	}
}
