// Code generated by eventgen. DO NOT EDIT.

package eventlog

const (
	EventTypeTaskSubmitted = "task.submitted"
)

// EventTypes lists every known envelope.type value (sorted).
var EventTypes = []string{
	EventTypeTaskSubmitted,
}

const CategoryBusiness = "business"
