// Code generated by eventgen. DO NOT EDIT.

package eventlog

import "strings"

// PartitionCard builds "card" partitions.
func PartitionCard(cardID string) string {
	return "card:" + strings.TrimSpace(cardID)
}

