// Code generated by eventgen. DO NOT EDIT.

package eventlog

import "encoding/json"

// TaskSubmittedPayload is generated from contracts.
type TaskSubmittedPayload struct {
	CardID string `json:"card_id"`
	Title string `json:"title"`
}

// PayloadTypeFor returns the concrete payload struct name for an event type, or "" if unknown.
func PayloadTypeFor(eventType string) string {
	switch eventType {
	case EventTypeTaskSubmitted:
		return "TaskSubmittedPayload"
	default:
		return ""
	}
}

// UnmarshalPayload decodes env.Payload into the correct struct for env.Type.
func UnmarshalPayload(env Envelope) (any, error) {
	switch env.Type {
	case EventTypeTaskSubmitted:
		var p TaskSubmittedPayload
		if err := json.Unmarshal(env.Payload, &p); err != nil {
			return nil, err
		}
		return &p, nil
	default:
		return nil, nil
	}
}
