// Code generated by eventgen. DO NOT EDIT.

package eventlog

import (
	"context"
)

// PublishTaskSubmitted appends a task.submitted envelope (category=business, version=1) outside a transaction.
func PublishTaskSubmitted(ctx context.Context, log Log, cardID string, p TaskSubmittedPayload, opts ...PublishOption) (int64, error) {
	var seq int64
	envs, err := log.Atomic(ctx, func(uow UnitOfWork) error {
		return PublishTaskSubmittedInTx(ctx, uow, cardID, p, opts...)
	})
	if err != nil {
		return 0, err
	}
	if n := len(envs); n > 0 {
		seq = envs[n-1].Seq
	}
	return seq, nil
}

// PublishTaskSubmittedInTx appends a task.submitted envelope inside an open UnitOfWork.
func PublishTaskSubmittedInTx(ctx context.Context, uow UnitOfWork, cardID string, p TaskSubmittedPayload, opts ...PublishOption) error {
	o := collectPublishOptions(opts)
	return uow.Append(ctx, EnvelopeDraft{
		Partition: PartitionCard(cardID),
		Type: EventTypeTaskSubmitted,
		Version: 1,
		Category: CategoryBusiness,
		Payload: p,
		Actor: o.actor,
		TraceID: o.traceID,
		SpanID: o.spanID,
	})
}

