// Code generated by eventgen. DO NOT EDIT.

package eventlog

import (
	"context"
	"encoding/json"
)

// PublishTaskSubmitted appends a task.submitted envelope (category=business, version=1).
func PublishTaskSubmitted(ctx context.Context, log Appender, cardID string, p TaskSubmittedPayload, opts ...PublishOption) (int64, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return 0, err
	}
	o := collectPublishOptions(opts)
	env := Envelope{
		Partition: PartitionCard(cardID),
		Type: EventTypeTaskSubmitted,
		Version: 1,
		Category: CategoryBusiness,
		Ts: NowRFC3339Nano(),
		Payload: b,
		Actor: o.actor,
		TraceID: o.traceID,
		SpanID: o.spanID,
	}
	return log.Append(ctx, env)
}

